[둘리] 1단계 블랙잭 제출합니다.
woowacourse/kotlin-blackjack pull request #21
Opened 2023-03-03 08:32 UTC by hyemdooly

안녕하세요, 리뷰어님!! 많이 배우겠습니다. 피드백 부탁드립니다! :)

2023-03-04 07:53 UTC, galcyurio requested changes
1단계 블랙잭 미션 고생하셨습니다.
클래스를 각 역할별로 잘 분리해주셨네요 :)
이번 단계에서는 UI 로직 분리와 테스트 코드에서 불필요한 정보를 없애는데에 초점을 맞춰보면 좋겠어요.

2023-03-04 07:53 UTC, galcyurio commented on src/main/kotlin/domain/CardPackGenerator.kt
> +        )
한 줄에서 너무 많은 처리를 하고 있습니다.
함수 또는 변수로 분리해보세요.

2023-03-04 07:53 UTC, galcyurio commented on src/main/kotlin/domain/CardPicker.kt
> +}
이 기능은 별도 클래스로 분리되기보다는 Cards, Card, Player와 같은 클래스에 구현되어야 하는 로직으로 보입니다.

별도의 CardPicker라는게 가상의 무언가가 존재하기보다는 카드를 pick하는 책임은 플레이어에게 있는게 조금 더 자연스럽게 느껴져요.

2023-03-04 07:53 UTC, galcyurio commented on src/main/kotlin/model/Card.kt
> +    }
UI 로직입니다. UI layer에서 데이터를 받아서 그리도록 만들어보세요.

2023-03-04 07:53 UTC, galcyurio commented on src/main/kotlin/model/Cards.kt
> +        }
UI 로직입니다. UI layer에서 데이터를 받아서 그리도록 만들어보세요.

2023-03-04 07:53 UTC, galcyurio commented on src/main/kotlin/model/Suit.kt
> +    DIAMOND("다이아몬드"), CLOVER("클로버"), SPADE("스페이드"), HEART("하트")
UI 로직입니다. UI layer에서 데이터를 받아서 그리도록 만들어보세요.

2023-03-04 07:53 UTC, galcyurio commented on src/main/kotlin/view/InputView.kt
> +        require(Regex("[$Y$y$N$n]").matches(input)) { IS_NOT_YES_OR_NO_ERROR }
Regex에서 내부적으로 사용하는 Pattern 인스턴스는 생성 비용이 높습니다.
재사용하는 방식으로 수정해보세요.

2023-03-04 07:53 UTC, galcyurio commented on src/test/kotlin/blackjack/domain/CardGameTest.kt
> +        }
`@BeforeEach`로도 충분해보여요.

2023-03-04 07:53 UTC, galcyurio commented on src/test/kotlin/blackjack/model/DealerTest.kt
> +            ),
테스트 본문에는 테스트하고자 하는 것을 이해할 수 있는 정보를 모두 가지고 있어야 하고, 반대로 불필요한 내용을 전부 감추어야 합니다.
- 참고: https://testing.googleblog.com/2014/03/testing-on-toilet-what-makes-good-test.html

------

여기서 불필요한 정보는 무엇인지 필요한 정보는 무엇인지 찾아보고 불필요한 정보들을 테스트 본문 바깥으로 분리해보세요.

2023-03-04 07:53 UTC, galcyurio commented on src/test/kotlin/blackjack/model/ParticipantsTest.kt
> +        )
indent가 굉장히 깊습니다.
여기서는 해당 이름으로 제대로 만들어지는지가 중요한 테스트 케이스같은데 불필요한 정보들을 분리해보세요.

2023-03-04 07:53 UTC, galcyurio commented on src/main/kotlin/model/Players.kt
> +data class Players(val players: List<Player>) : List<Player> by players
일급 컬렉션을 구현할 때는 외부에 데이터를 전달하기보다는 메시지를 받아서 내부에서 처리한 후 외부에 결과를 반환하는게 좋습니다.
하지만 컬렉션을 구현하고 위임하도록 처리해버리면 습관적으로 컬렉션을 쓰듯이 사용하게되어서 나쁜 습관이 만들어집니다.
이번 미션에서는 위임을 쓰지 않고 만들어보세요.

하지만 외부에서 해당 데이터가 반드시 필요한 경우도 있는데 이런 경우에는 아래와 같은 함수를 통해 방어적 복사를 한 이후 드러내주세요.

```kotlin
fun toList(): List<Foo> = values.toList()

fun toSet(): Set<Foo> = values.toSet()
```

2023-03-05 07:57 UTC, hyemdooly commented on src/main/kotlin/model/Players.kt
> +data class Players(val players: List<Player>) : List<Player> by players
피드백 반영 중 궁금한 점이 있어 질문드립니다.
List의 element가 가변객체인 경우, toList()가 가변객체까지 복사해주지는 않는 것으로 알고 있습니다.
해당 미션에서는 print하기 위해서를 제외하고는 toList()를 실행할 일은 없는데요!
그래도 무조건 가변객체 복사까지 구현해주어야하는지, 용도에 따라 List만 복사해도 되는지 궁금합니다! :)

2023-03-05 15:11 UTC, galcyurio approved these changes
1단계 미션 고생하셨습니다 👍 
몇 가지 피드백을 남겨두었는데 다음 단계에서 같이 반영해주세요!

2023-03-05 15:11 UTC, galcyurio commented on src/test/kotlin/blackjack/domain/CardGameTest.kt
> +    }
참고로 junit4, junit5에서는 각 테스트 케이스를 수행하기 전에 테스트 클래스를 새로 만드는게 기본 설정이라 실제로는 `@BeforeEach`도 필요없습니다.
하지만 가독성과 추후에 필요해지는 경우도 생기므로 지금처럼 초기화 코드를 분리해주시는게 좋습니다.

만약 필요하다면 `@TestInstance(Lifecycle.PER_CLASS)`를 통해 한 번만 인스턴스가 만들어지도록 할 수도 있습니다.

2023-03-05 15:11 UTC, galcyurio commented on src/main/kotlin/model/Participant.kt
> +    }
더욱 코드가 객체지향적이 되었네요 👍

2023-03-05 15:11 UTC, galcyurio commented on src/main/kotlin/model/Cards.kt
> +    }
LinkedList와 같이 이미 잘 만들어져있는 자료구조를 활용해봐도 좋겠네요.

2023-03-05 15:11 UTC, merged