[부나] 1단계 블랙잭 제출합니다.
woowacourse/kotlin-blackjack pull request #29
Opened 2023-03-03 08:48 UTC by tmdgh1592

블랙잭 미션을 완료하였습니다!
미션 마감까지 시간이 얼마 남지 않아 궁금한 점에 대해 추후에 추가로 남기겠습니다..! 🥲
감사합니다!

2023-03-03 14:15 UTC, laco-dev requested changes
안녕하세요.
블랙잭 미션동안 잘 부탁드립니다.

객체지향을 학습하는 과정인 만큼,
참가자라는 하나의 역할 안에서 딜러와 플레이어가 각각 어떤 공통점과 차이점을 가지는지 잘 고민 해보셨으면 좋겠습니다.

그 외에 전반적으로 구조 변경이 필요한 부분이 많아서 컨트롤러와 테스트 작성 부분은 피드백 반영 후에 다시 확인하도록 하겠습니다. 🙏🏻

2023-03-04 06:52 UTC, tmdgh1592 commented on src/main/kotlin/blackjack/dto/HandDTO.kt
> +)
DTO는 각 계층간 데이터를 전달하기 위한 목적을 가지고 있습니다.
따라서 어떠한 로직을 포함하고 있어서도 안됩니다.

가령 View에서 Domain 객체를 직접 의존한다면, Domain이 변경되었을 때 View 또한 수정되어야 할 가능성이 높다고 생각이 듭니다.
또한, View에서 의도치 않게 Domain 로직을 수행할 수 있는 가능성까지 발생합니다.
그렇기 때문에 각 계층간 의존을 덜어내면서, 값을 전달하기 위한 목적으로 DTO를 사용한다고 알고 있습니다.

MVC패턴에서 Controller는 View와 Domain의 중개 역할을 수행하며, View와 Domain을 의존합니다. 따라서 Controller에서 DTO를 사용하여 Domain 로직을 통해 얻은 결과를 View에게 전달해주는 것이 좋지 않을까 라는 생각을 하였습니다.

2023-03-04 06:55 UTC, tmdgh1592 commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +    private lateinit var blackJack: BlackJack
BlackJackController의 start() 메서드를 호출할 때마다 새로운 인스턴스로 초기화되므로 따로 뺴놓을 필요가 없을 것 같습니다!

2023-03-04 06:57 UTC, tmdgh1592 commented on src/main/kotlin/blackjack/domain/CardNumber.kt
> +value class CardNumber(private val number: Int) {
각 모양이 4가지로 정해져 있기 때문에 enum으로 만든 것처럼 끗수 또한 명확하게 정의되어 있으므로 enum으로 분리할 수 있을 것 같습니다!
그렇게 되면 각 끗수가 의미하는 점수 또한 관리할 수 있을 것으로 예상됩니다!

2023-03-04 06:57 UTC, tmdgh1592 commented on src/main/kotlin/blackjack/domain/Command.kt
> +}
입력 값이 달라지는 상황에서도 domain을 재사용할 수 있게끔 만드는 것이 중요하다는 생각이 들었습니다. 일례로, 한국을 타겟으로 하다가 앱을 글로벌화 했을 때, 각국 다른 언어로 이루어진 입력값에 따라 domain을 수정하거나 새롭게 만드는 것은 유지보수에 좋지 않을 수도 있기 때문입니다.

따라서 남겨주신 “받는다”, “받지 않는다”를 어떻게 처리할지 고민해볼 필요가 있을 것 같습니다.
처음에 단순히 입력의 길이로만 체크해볼까 했는데 이 또한 View에서 처리해주어야 할 문제인 것 같아서 페어와 함께 고민해보겠습니다!

2023-03-04 06:58 UTC, tmdgh1592 commented on src/main/kotlin/blackjack/domain/Shape.kt
> +}
Encoding 설정에 따라서 한글이 깨지는 경우가 발생할 수 있기 때문에, 영어로 작성하는 것이 일반적일 것 같습니다.

2023-03-04 07:10 UTC, tmdgh1592 commented on src/main/kotlin/blackjack/domain/BlackJackBuilder.kt
> +}
> 빌더는 어떠한 공유 자원을 사용하지 않습니다.

Builder는 어떠한 공유 자원을 사용하지 않아야 하는데, 위 코드에서는 cardDeck이 generator라는 공유자원을 사용하고 있습니다..!

> 빌더가 생성하는 인스턴스를 만들기 위해 반드시 필요한 값이라면, 선택적으로 받지 않습니다.
> 즉, 이 경우 생성자를 이용해서 받는것이 맞습니다.

다시 살펴보니, 말씀해주신 것처럼 단순히 `val blackJack = BlackJackBuilder { }` 라는 코드를 작성했을 때 문제가 발생하게 됩니다..😅 
Builder 패턴을 사용할 때에는 반드시 필요한 값이 아닌, 선택적으로 초기화가 필요한 경우에 사용하는 것이 올바른 사용법이라는 생각이 들었습니다.
그 외에 필수적으로 인스턴스 생성에 필요한 값이라면 생성자를 이용하는 것이 좋을 것 같습니다!!

> 지금 구조에서 빌더 + DSL을 사용하는 것에 특별한 장점이 드러나지 않는 것 같습니다.

이번에 우테코 강의에서 DSL을 배워서 적용해보고 싶은 마음에 해봤는데, 3번 피드백을 받고 찾아보니, 빌더와 DSL을 함께 사용하는 경우는 어떠한 인스턴스를 생성하는 것이 복잡한 구조일 때 적합하다고 합니다.
리뷰어님께서 특별한 장점이 드러나지 않는다는 말씀의 의미는 생성자처럼 더 간단한 구조를 사용하기를 권장하시는 말씀이신지 여쭤봐도 될까요?!

2023-03-04 07:13 UTC, tmdgh1592 commented on src/main/kotlin/blackjack/domain/Card.kt
> +    override fun toString(): String = "${number.toLetter()}${shape.name}"
도메인은 비즈니스 로직만을 수행하고, 로직에 의해서 반환된 값을 어떻게 화면에 보여주는지는 View에 따라 다를 수 있다고 다시금 생각이 들었습니다.
어떤 View에서는 Shape.Heart를 “하트” 라고 그리고 싶어하고, 또 다른 View에서는 하트를 “❤️”로 그리고 싶어한다면, 그 때마다 domain을 수정해주는건 재사용성이 매우 떨어지기 때문입니다.

2023-03-04 07:14 UTC, tmdgh1592 commented on src/main/kotlin/blackjack/domain/Card.kt
> +        }.flatten()
감사합니다! 🙂

2023-03-04 07:15 UTC, tmdgh1592 commented on src/main/kotlin/blackjack/domain/CardDeck.kt
> +}
단순히 카드를 하나 뽑는데 그 때마다 계속 generate() 해주는 것이 자연스러운 구현은 아닌 것 같습니다.
CardDeck의 생성자 파라미터로 generator 대신에 이미 생성된 카드들을 넘겨주는 방식으로 변경해보겠습니다!

2023-03-04 07:18 UTC, tmdgh1592 commented on src/main/kotlin/blackjack/domain/GameResult.kt
> +        }
이렇게 구현하면 Dealer가 Player를 상속하고 있기 때문에, Dealer의 승패 여부와 Player의 승패 여부를 각자 판단할 수 있겠네요! 😲

2023-03-07 12:28 UTC, laco-dev requested changes
피드백 반영 잘 해주셨습니다.
이전보다 훨씬 구조가 잘 만들어진 것 같아요. 👍🏻 

다만 아직은 명시적으로 딜러 플레이어를 너무 잘 알고있다보니 코드가 자연스럽게 딜러랑 플레이어를 직접 호출하는 형태로 작성이 된 것 같습니다.

딜러나 플레이어가 스스로 판단할 수 있도록 참가자 타입을 조금더 잘 활용해 보셨으면 좋겠습니다.

관련해서 피드백 몇가지 남겨드렸으니 확인 부탁드리고, 다음 PR 요청에는 머지될 수 있도록 하겠습니다.

2023-03-07 12:28 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/BlackJack.kt
> +    }
처음 카드를 받는 동작과 게임을 시작하는 과정으로 크게 두가지로 나눠서 생각해볼 수 있지 않을까요?

```kotlin
class BlackJack(...) {
   // 카드 2장을 준비하는 과정
   fun readyToStart() {
      participants.drawFirst(deck)
   }

   fun start(onDrawn: (Participant) -> Unit): BlackJackResult {
      while (isRunning()) {
         participants.draw(deck)
         ...
      }
   }
```

2023-03-07 12:28 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/BlackJack.kt
> +    fun getTotalScores(): Map<String, Int> = participants.getTotalScores()
개인적으로 드는 생각은 `Map<String, List<Card>>` 타입을 만드는 것이 UI 때문에 만들어진 것 처럼 느껴집니다.

만약 플레이어의 이름, 나이, 카드들을 출력해야 한다면 위 함수의 변경이 불가피합니다.
결국 필요한 것은 참가자로부터 정보를 가져오는 것이기 때문에 직접적으로 호출을 하는것이 더욱 자연스럽지 않을까? 생각이 들어요

```kotlin
val participants: Participants = (dealer + players)
val blackJack = BlackJack(deck, participants)

blackJack.readyToStart()
OutputView.printFirstDrawn(participants) // 안에서 이름이나 카드들을 출력하게끔 유도

val result = blackjack.start(
   onDrawn = { participant -> OutputView.printDrawn(participant) }
)
OutputView.printResult(result)
```

이 구조를 지원하려면 플레이어가 InputView와 인터페이스를 이용한 협력관계가 필요할 수도 있습니다.

```kotlin
class Player(needToDraw: () -> Boolean) {
   override fun canDraw() = !cards.isBust() && needToDraw() 
}
```

2023-03-07 12:28 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Players.kt
> +class Players(private val players: List<Player>) {
앞선.. 이유들 때문에? Players 객체가 정말 필요한가 라는? 의문으로 이어졌네요 😅
한번 고민 해보시고, 필요하다 생각되면 유지 해주세요

2023-03-07 12:28 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/PlayerResults.kt
> +}
Map 형태로 만드는 것보다 단순하게 생각해 볼 수 있지 않을까요?
이렇게 하면 플레이어나 딜러 상관없이 사용이 가능할 것 같네요
```kotlin
class MatchResult(
   val participant: Participant,
   val winCount: Int,
   val loseCount: Int,
   val drawCount: Int
) 
```

2023-03-07 12:28 UTC, laco-dev commented on src/test/kotlin/blackjack/domain/CardNumberTest.kt
> +    }
ParameterizedTest를 사용한다면 테스트 이름에 인자를 넣어서 출력할 수 있어요.
예를 들어 위 테스트는 아래와 같이 보이도록 할 수 있겠습니다.
```kotlin
"ACE 카드는 1점이다"
"JACK 카드는 10점이다"
```

ParameterizedTest의 사용 방법에 대해 한번 찾아보세요.

2023-03-07 12:28 UTC, laco-dev commented on src/test/kotlin/blackjack/domain/CardsTest.kt
> +        cards.add(Card(CardNumber.FIVE, Suit.SPADE))
카드 목록에 카드를 추가하기위해 add() 함수를 여러번 호출해야 하는 귀찮음(?) 이 발생할 수 있는데요.

생성자로 처음 카드들을 초기화 할 수 있다면 이렇게 작성할 수 있지 않을까요?
```kotlin
val cards = Cards(
   Card(...),
   Card(...),
   Card(...)
)
```

2023-03-07 12:28 UTC, laco-dev commented on src/test/kotlin/blackjack/domain/DealerTest.kt
> +    }
카드들의 점수합계는 Cards에서 이미 테스트하고 있다고 볼 수 있어요.
그렇기 때문에 딜러나 플레이어와 Cards에 중복으로 같은 테스트가 작성이 되었다는 뜻인데요.

이 부분은 트레이드 오프의 영역이기는 합니다.
테스트 커버리지를 높일것인지, 역할에 맞는 테스트만 수행할 것인지.

가령, 보너스 점수가 11점으로 수정이 된다면 딜러, 플레이어 테스트가 터지게 됩니다 <

2023-03-07 12:28 UTC, laco-dev commented on src/test/kotlin/blackjack/domain/ParticipantsTest.kt
> +}
불필요한 테스트 코드라면, 삭제해주세요

2023-03-07 12:28 UTC, laco-dev commented on src/test/kotlin/blackjack/domain/PlayerResultsTest.kt
> +    }
playerResulst가 따로 위치해있어서 이게 어떤 결과가 나와야 정상인지...? 찾는 과정이 오히려 불편하게 다가오네요.. 😓 

아래 방식과 한번 비교 해보시고, 필요하다면 개선 해보셔도 좋습니다
```kotlin
fun `부나의 점수가 17점, 딜러의 점수가 20점이라면 딜러는 1승이다`() { ... }

fun `부나의 점수가 15점, 딜러의 점수가 15점이라면, 딜러는 1무이다`() { ... }

fun `부나의 점수가 20점, 딜러의 점수가 15점이라면, 딜러는 1패이다`() { ... }
```

2023-03-07 12:31 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/BlackJackBuilder.kt
> +}
명확한 생성자 호출을 하는 구조이기 때문에 DSL을 사용할 필요가 없다는 뜻이었습니다.
```kotlin
val blackjack = Blackjack(...)

val blackjack = Blackjack { 
   foo(...)
   bar(...)
}
```

2023-03-09 11:39 UTC, laco-dev approved these changes
피드백 반영 해주실 때마다 구조가 크게 발전하는 것 같아서 좋았어요.
다음단계 진행하기 전에 도움될만한 내용을 몇가지 남겨보았습니다.

2단계의 수익을 계산하기 위해서는 단순히 카드의 점수만 계산하는 것이 아닌 카드의 상태라는 개념으로 접근하면 좋습니다. 👍🏻 

이 내용 참고하셔서 구현 해주시면 될 것 같습니다. 💪🏻

2023-03-09 11:39 UTC, laco-dev commented on src/main/kotlin/blackjack/controller/BlackjackController.kt
> +    }
함수를 분리하지 않아도? 괜찮아 보여요!
setupCard()와 drawInitialCards()가 어떤 차이인지 헷갈림!

2023-03-09 11:39 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Blackjack.kt
> +    fun getFirstOpenCards(): Map<String, List<Card>> = participants.getFirstOpenCards()
좋습니다. 
조금 더 나아가 본다면, start() 함수 하나에서 처음 뽑을 카드와 이어서 뽑는 카드들을 같이 묶을 수 있을 것 같네요!

```kotlin
fun start(onDrawn: (Participant) -> Unit): Result {
   participants.drawFirst(deck, onDrawn)
   participants.draw(deck, onDrawn)

   return ...
}
```

2023-03-09 11:39 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/BlackjackResult.kt
> +    val matchResults: List<MatchResult>,
CardResult랑 MatchResult를 나눌 필요가 있을까요?
플레이어의 입장에서도 승, 패, 무를 비교한다면 1승 0무 0패 처럼 나타낼 수 있지 않을까요?

2023-03-09 11:39 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Cards.kt
> +    }
_items 프로퍼티를 만들면서 생성자로 받은 cards를 초기화 할 수 있어요

2023-03-09 11:39 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Cards.kt
> +        private const val STAY_SCORE = 17
블랙잭 게임에서 스테이라는 의미는 어떠한 점수를 나타내는 상태가 아닙니다.
카드들의 개념보다는 정확하게는 "딜러"가 카드를 더 뽑기 위한 조건 이라고 보는게 맞을 것 같습니다

```
21점 미만일 때, 더 뽑는다 -> 히트
21점 미만일 때, 더 뽑지 않는다 -> 스테이
21점 초과일 때 -> 버스트
```

2023-03-09 11:39 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Participant.kt
> +        isBust() && other.isBust() -> GameResult.DRAW
블랙잭 규칙에서는 상대의 점수가 무엇이든지 상관없이 자신이 버스트라면 패배입니다.

2023-03-09 11:39 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Participant.kt
> +        getTotalScore() > other.getTotalScore() -> GameResult.WIN
이 함수를 끝내기까지 getTotalScore()가 몇번 호출이될까요?
가독성을 위해 위처럼 작성을 할 수 있겠지만, 불필요한 호출은 줄이면 좋을 것 같아요

2023-03-09 11:39 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Participants.kt
> +    }
딜러와 플레이어를 나눠서 턴을 가져갈 필요가 있을까요?

2023-03-09 11:39 UTC, merged

2023-03-09 11:48 UTC, tmdgh1592 commented on src/main/kotlin/blackjack/controller/BlackjackController.kt
> +    }
앗 그렇군요..!
어차피 한 줄이고 굳이 나누지 않는 것이 가독성이 좋아보입니다!

2023-03-09 16:12 UTC, tmdgh1592 commented on src/main/kotlin/blackjack/domain/Participants.kt
> +    }
다시 살펴보니 그럴 필요가 없다는 걸 알게 됐습니다! 🤔
처음에 단순히 `participants.forEach` 와 같이 하다보니 `딜러 -> 플레이어` 순으로 카드를 뽑게 되는 문제가 있어 각각 분리하였습니다.
하지만 `(getPlayers() + getDealer()).forEach` 이와 같은 방식으로 변경하니 정상적으로 프로그램이 동작합니다!

2023-03-10 06:26 UTC, tmdgh1592 commented on src/main/kotlin/blackjack/domain/Participant.kt
> +        isBust() && other.isBust() -> GameResult.DRAW
그렇군요..! 제가 규칙을 잘못 이해하고 있었던 것 같습니다!
2단계 미션을 진행하면서 수업시간에 배운 State, Template Method 패턴을 함께 적용하면서 리팩터링해보겠습니다.
만약 `Dealer의 상태가 블랙잭이고, Player의 상태가 블랙잭이면 Draw를 반환한다.` 와 같이 작성해볼 수 있을 것 같습니다!

2023-03-10 16:34 UTC, tmdgh1592 commented on src/main/kotlin/blackjack/domain/Cards.kt
> +        private const val STAY_SCORE = 17
2단계와 피드백을 보면서 깨달았습니다..
아직 Blackjack이라는 도메인 지식이 부족한 것 같습니다.
`스테이는 더 뽑지 않는다` 라는 의미이군요.
감사합니다!