[둘리] 2단계 블랙잭 제출합니다
woowacourse/kotlin-blackjack pull request #35
Opened 2023-03-07 09:00 UTC by hyemdooly

안녕하세요, 리뷰어님! 1단계 피드백을 반영하고 2단계 기능을 구현하였습니다.
제가 봐도 아직 코드가 부족하다고 생각하는데, 혼자 고민해도 어려워서 질문드립니다!

1. 객체가 일을 해야한다고 생각해서 Player에 판단하는 기능을 넣었는데, judge 함수를 따로 다른 클래스에 빼는 것이 좋을까요?
2. 컨트롤러나 테스트코드에서 초기화하는 코드가 너무 복잡한 경우 DSL을 이용한 빌더를 작성해주는 것이 좋을까요? (Ex. Controller의 initBetInfo)
3. CardGame과 컨트롤러의 경계를 어떻게 지어야할지 감이 잘 안옵니다. 컨트롤러가 되도록 로직을 몰라야한다고 생각해서 CardGame에 분리하여 작성하려고 노력했는데요. 게임 진행 중 View가 필요한 순간이 계속해서 등장해서 어렵습니다. ㅠㅠ 
다른 크루들의 의견을 들어보니 CardGame에 View의 함수를 인자로 넘겨주었다고 하는데요.
저는 도메인에서 View의 함수를 사용하는 일은 피해야한다는 입장입니다!  도메인에서 View의 함수를 사용하는 것이, 도메인에서는 View에서 오는 함수인지 모른다고 할지라도 MVC에 위배되지 않는건가요?

2023-03-07 15:58 UTC, galcyurio requested changes
2단계 잘 진행해주셨네요 :)
몇 가지 피드백을 남겨두었으니 확인 후 다시 요청해주세요.

2023-03-07 15:58 UTC, galcyurio commented on src/main/kotlin/domain/CardGame.kt
> +class CardGame(val cardPack: CardPack) {
> CardGame과 컨트롤러의 경계를 어떻게 지어야할지 감이 잘 안옵니다. 컨트롤러가 되도록 로직을 몰라야한다고 생각해서 CardGame에 분리하여 작성하려고 노력했는데요. 게임 진행 중 View가 필요한 순간이 계속해서 등장해서 어렵습니다. ㅠㅠ 
다른 크루들의 의견을 들어보니 CardGame에 View의 함수를 인자로 넘겨주었다고 하는데요.
저는 도메인에서 View의 함수를 사용하는 일은 피해야한다는 입장입니다!  도메인에서 View의 함수를 사용하는 것이, 도메인에서는 View에서 오는 함수인지 모른다고 할지라도 MVC에 위배되지 않는건가요?

고차함수를 받는 것으로는 MVC에 위배되지 않습니다.
위배되지는 않으나 `showXxx()`, `printXxx()`와 같은 이름이라면 code smell로 여겨집니다.

조금 다르게 생각해보세요.
- as-is: domain에서 특정 상태가 되면, ui에서 넘어온 함수를 호출한다.
- to-be: domain에서 특정 상태가 되면, 해당 상태를 외부로 노출한다.

쉽게 이야기하자면, 외부에서 domain 클래스에 Listener 또는 콜백 함수를 선언할 수 있도록 만들어보라는 뜻입니다.
또는 고차 함수로 받을 수도 있습니다. 
또한 `showXxx()`와 같은 UI 중심의 이름이 아닌 `onXxx()` 형태로 domain 중심으로 이름이 지어져야 합니다.

2023-03-07 15:58 UTC, galcyurio commented on src/main/kotlin/model/Cards.kt
> +data class Cards(val cards: LinkedList<Card>) {
`cards`를 private으로 변경해주세요.
외부에서 `cards`를 곧바로 접근할 수 있기 때문에 의도치 않게 값을 변경할 수 있습니다.

`cards`를 직접 접근해서 데이터를 꺼내므로 일급컬렉션으로 선언한 의미가 사라져버렸습니다.
조금 boilerplate code라고 느껴지더라도 간접적으로 변경하도록 만들어주세요.

정말 필요한 경우에만 `toList(): List<Card>`와 같은 함수에서 방어적 복사를 한 이후에 노출시켜주세요.

2023-03-07 15:58 UTC, galcyurio commented on src/main/kotlin/view/RankModel.kt
> +}
ui layer에서만 쓰기 위한 모델 :+1:

2023-03-07 15:58 UTC, galcyurio commented on src/main/kotlin/view/InputView.kt
>          require(input.isNotBlank()) { NULL_ERROR }
잘못된 입력이 들어온 경우 프로그램이 예외가 던져져서 강제 종료되기보다는 재입력을 받도록 만들어보세요.

-----

다음은 코틀린에서의 예외처리 방식입니다.

- [논리 오류](https://ko.wikipedia.org/wiki/%EB%85%BC%EB%A6%AC_%EC%98%A4%EB%A5%98)일 때만 예외를 던지세요.
  - 최대한 논리 오류가 되지 않도록 만드세요.
  - 그럼에도 불구하고 논리 오류가 발생하는 경우 예외를 던지세요.
  - 여기서 던져진 예외는 전역적으로 잡아서 에러를 리포팅하세요. (Thread.setDefaultUncaughtExceptionHandler)
- 논리 오류가 아니면 예외를 던지지 말고 null을 반환하세요.
- 실패하는 경우가 복잡해서 null로 처리할 수 없으면 sealed class를 반환하세요.
- 일반적인 코틀린 코드에서 `try-catch`를 사용하지 마세요.

위 사항들의 자세한 설명은 아래 글을 읽어보세요.
[https://medium.com/@elizarov/kotlin-and-exceptions-8062f589d07](https://medium.com/@elizarov/kotlin-and-exceptions-8062f589d07)

2023-03-07 15:58 UTC, galcyurio commented on src/main/kotlin/model/GameResult.kt
> +    fun getDealerProfitResult(): Int = filterSum { it < 0 } + filterSum { it > 0 }
바로 모두 더해버리는건 어떨까요?

```kotlin
fun getDealerProfitResult(): Int = playersFinalResult.values.sum() * -1
```

2023-03-07 15:58 UTC, galcyurio commented on src/main/kotlin/model/Hand.kt
> +    }
정보를 가지고 있는 Cards에서 처리하도록 만들어보세요.

2023-03-09 09:13 UTC, hyemdooly commented
피드백을 반영하면서 컨트롤러를 크게 고쳤습니다!
컨트롤러는 게임의 로직을 되도록 몰라야한다고 해서, CardGame에 InputView와 OutputView를 고차함수로 넘겨주어 사용하는 방식을 사용했는데요.
기존 방법이 더 좋은지, 지금 방법이 더 좋은지 궁금합니다.
추가로 더 개선될 수 있는 부분이 있다면 피드백 부탁드립니다. 감사합니다! :)

2023-03-09 17:11 UTC, galcyurio commented on src/main/kotlin/domain/CardGame.kt
> +class CardGame(private val cardPack: CardPack, private val onError: (String) -> Unit) {
> 컨트롤러는 게임의 로직을 되도록 몰라야한다고 해서, CardGame에 모든 로직을 구현하고 InputView와 OutputView의 함수를 넘겨주어 고차함수를 쓰는 방식을 사용했는데요.
기존 방법이 더 좋은지, 지금 방법이 더 좋은지 궁금합니다.

각 layer의 역할을 침범하지만 않는다면, 지금처럼 최대한 domain layer로 관련 로직을 옮겨주면 좋습니다.
그 이유는 domain layer가 가장 테스트하기 쉬운 layer이기 때문입니다.

presentation layer에 해당하는 controller에 대한 테스트 코드와 ui layer에 해당하는 InputView, OutputView에 대한 테스트 코드를 작성해야 한다고 생각해보면 왜 domain layer로 옮겨야 하는지 이해하기 쉬울거에요.

2023-03-09 17:14 UTC, galcyurio commented on src/main/kotlin/domain/CardGame.kt
> +    }
`getName()`으로 넘기기보다는 UI layer에서 재입력을 받도록 처리하고 domain layer에서는 올바른 입력만 들어오도록 만들어보세요.
domain에서는 ui를 알지 못해야하지만 ui 에서는 domain을 알아도 됩니다.
이 점을 활용해보세요.

2023-03-09 23:52 UTC, hyemdooly commented on src/main/kotlin/domain/CardGame.kt
> +class CardGame(private val cardPack: CardPack, private val onError: (String) -> Unit) {
이해했습니다, 감사합니다!

2023-03-10 15:05 UTC, merged