[핑구] 2단계 블랙잭 제출합니다.
woowacourse/kotlin-blackjack pull request #41
Opened 2023-03-09 08:11 UTC by pingu244

안녕하세요 잭슨님

지난번 피드백에 대한 생각들입니다!

> 객체의 책임과 구조에 대해 한번 고민해보아요!

딜러와 플레이어에서 발생하는 중복 코드를 제거해야 한다는 요구 사항이 있어서 무조건적으로 상속을 생각했었습니다. 
그런데 주신 피드백을 바탕으로 생각해보니 전에 있던 ParticipantCards를 Player와 Dealer 객체의 인자로 갖게 하여 조합 형태로 수정했습니다.
또한 checkOverCondition은 카드를 가진 객체가 수행해야할 기능인 것 같아 Player, Dealer객체에 따로 만들어주었습니다.

> Referee는 필요한 객체일까요?

승무패를 판단해주는 객체가 따로 있었으면 좋겠다고 생각해서 Referee가 꼭 필요하다고 생각을 했습니다.
그런데 다른 크루의 말을 들어보니 결국 블랙잭이라는 게임이 여러명이 경쟁하는 것이 아닌 '딜러 vs 플레이어'의 형태이기 때문에 굳이 Referee를 만들 필요가 없다는 의견이 있었습니다.
그래서 생각해보니 결국 판단은 딜러가 하는 것이 아닐까 생각되어 Dealer 객체에서 승무패를 판단하는 기능을 넣게 되었습니다.
이렇게 정리하니 이전보다 훨씬 깔끔해진 것 같아 뿌듯했습니다😊

---

이렇게 구조를 바꾸며 생긴 질문이 몇 가지 있습니다!

1. 설계할 때 잭슨님만의 접근 방법이 있을까요..? 
물론 경험을 쌓아가며 설계 실력도 느는 것이지만 설계가 너무 막막하고 어려워서 여쭈어봅니다..😂

2. BlackjackGame을 테스트하기 위해서는 BlackjackGame의 private 변수인 players와 dealer를 public으로 돌려야하는데 테스트만을 위해서 그래도 되는 것인지 궁금합니다.

3. BlackjackGame에 있는 함수들이 이미 테스트가 완료된 기능에 view 기능만 추가한 것이 대부분입니다. 그래서 이것을 다시 테스트하는 것은 비효율적이라고 생각이 되었습니다. BlackjackGame은 어떻게 테스트하는 것이 좋을까요?

4. input에서 잘못된 입력인 경우 null로 받아 controller에서 처리(반복 입력)하게 했습니다. 그런데 다른 크루들을 보니 이 처리를 view안에서 끝내서 controller에는 완전한 값을 가져오게 하였습니다. (Controller의 기능을 줄이고 싶어 지금은 저도 이렇게 한 상태입니다)
개인적으로는 이렇게 view에서 반복처리를 한다면 view 내부에서 일어나는 예외 사항에 controller가 접근할 수 없기 때문에 null값에 대한 처리는 controller에서 하는 것이 낫다고 생각됩니다.
리뷰어님 입장에서는 어떤 것이 더 나은 방법인 것 같으신가요?
물론 정답은 없겠지만 잭슨님의 의견이 궁금하여 여쭤봅니다!

5. 현재 Player는 name, ownCards, bettingMoney, result 이렇게 4가지의 정보를 가지고 있습니다.
생성자 인자에 다 넣을 수는 없으니 var로 만들었는데 이러면 결국 외부에서 수정이 가능하게 됩니다.
근데 결국 외부에서 수정이 가능하긴 해야합니다..! 외부에서 계산하여 or 입력받아 정보를 저장해야하기 때문입니다..
이렇게 가변 객체로 만들기 싫은데 바깥에서 변경할 수는 있어야 하는 상황에서는 어떻게 해야 할까요?

질문이 너무 많아졌네요😅
정성스러운 피드백 항상 감사드립니다!

2023-03-10 02:32 UTC, namjackson commented
> 설계할 때 잭슨님만의 접근 방법이 있을까요..?
> 물론 경험을 쌓아가며 설계 실력도 느는 것이지만 설계가 너무 막막하고 어려워서 여쭈어봅니다..😂

어려운 질문이네요 😢 
사실 설계와 구현에는 다양한 방법이 있고, 정답이 없는 부분이기 때문에, 간단하게 말씀드릴순 없지만
먼저 객체의 책임을 고민해보면 어떨까요?
저는 전체적인 플로우를 그리고, 요구사항에 맞는 책임을 정하고, 
해당 책임을 수행하는 객체를 설계하곤 합니다
여러 설계 방법이나, 다양한 패턴이 존재하기 때문에, 학습하셔서 핑구님만의 설계방식, 코딩철학을 만드셔도 좋을거같아요 👍

2023-03-10 02:32 UTC, namjackson requested changes
안녕하세요 핑구님 
2단계 고생하셨습니다!
몇가지 고민할법한 포인트와 답변을 코멘트로 남겼으니, 확인해주세요!

2023-03-10 02:32 UTC, namjackson commented on src/test/kotlin/domain/BlackjackGameTest.kt
>  class BlackjackGameTest {
> BlackjackGame을 테스트하기 위해서는 BlackjackGame의 private 변수인 players와 dealer를 public으로 돌려야하는데 테스트만을 위해서 그래도 되는 것인지 궁금합니다.

먼저 테스트를 위한 코드는 지양하는게 좋아요, 
테스트를 위한 코드가 된다면, 좋은 방법은 아닙니다!
BlackjackGame의 어떤 테스트 작성을 위해 고민하시는걸까요?

다양한 방법이 있을 것 같아요!
먼저 불변객체라면, 불변변수에 사용해서 open해주어도 좋고,
생성자로 주입받는 방식을 활용할수도 있고, 
결과를 확인하기 위해서라면, 리뷰에 남겨진대로, 게임 결과값을 리턴하는 구조 로 변경할수 있을거 같아요
또 Private fun을 테스트하고 싶다면, 클래스 분리의 신호로 볼수도 있을거 같아요!

2023-03-11 14:34 UTC, pingu244 commented on src/main/kotlin/controller/BlackjackController.kt
> +        blackjackGame.showWinningResult(OutputView::printProfitResult)
제 생각에는 람다를 이용한다면 controller에서 맡는 일이 적어지고,
결과를 리턴받는다면 람다보다 직관적으로 하는 일을 확인할 수 있는 것 같습니다.

2023-03-11 14:40 UTC, pingu244 commented on src/main/kotlin/domain/participants/Player.kt
> +        private set
Player라던가 BlackjackGame에서 생성자 인자로 받아오는 정보들이 3개가 되는데 이를 줄일 수 있는 방법이 있을까요?
제가 생각한 방법은 클래스를 만들어서 두가지 프로퍼티를 하나의 객체로 관리하는 것인데, 
둘의 연관성이나 효율적인 코드를 위해서가 아닌 인자를 줄이고자 이렇게 만드는 것은 비효율적인 것 같습니다. (접근할 때 계속해서 파고 들어가야 하니까요!)

2023-03-12 12:03 UTC, namjackson requested changes
안녕하세요 핑구님! 
피드백 적용 잘해주셨네요,
마지막으로 몇가지 고민할법한 코멘트 남겼으니, 확인해주세요 😄

2023-03-12 12:03 UTC, namjackson commented on src/main/kotlin/domain/participants/Player.kt
> +class Player(val name: String, val ownCards: Cards, val bettingMoney: Money) {
> Player라던가 BlackjackGame에서 생성자 인자로 받아오는 정보들이 3개가 되는데 이를 줄일 수 있는 방법이 있을까요?
> 제가 생각한 방법은 클래스를 만들어서 두가지 프로퍼티를 하나의 객체로 관리하는 것인데,
> 둘의 연관성이나 효율적인 코드를 위해서가 아닌 인자를 줄이고자 이렇게 만드는 것은 비효율적인 것 같습니다. (접근할 때 계속해서 파고 들어가야 하니까요!)

두가지를 묶는다면, bettingMoney와 Cards를 묶어서 게임을 진행시키는 클래스로 분리할수 있다고 생각이 들지만, 
지금의 구조에선, 저도 핑구님의 생각처럼 불필요하다고 생각이들어요,
3가지 이상의 변수를 가진 클래스를 쓰지 않는다라는 요구사항이 있지만, 
좋은 설계를 위한 하나의 규칙일뿐, 불필요하다고 느낀다면 굳이 적용할필요는 없다는 생각이 들어요 😄 
좋은 설계방법을 고민해보시고, 불필요하다고 느끼시면 적용하지 않으셔도 좋을거 같아요!

2023-03-13 13:52 UTC, namjackson approved these changes
안녕하세요 핑구님! 
피드백 적용 잘해주셨네요! 💯 
추가로 드릴 피드백이 보이지 않아서, 미션은 이대로 종료하겠습니다!
블랙잭 미션 고생하셨습니다! 미션과정동안 의미있는 시간이 되었길 바랍니다! 👍 👍 
다음 미션들도 계속 응원하겠습니다 💪

2023-03-13 13:52 UTC, namjackson commented on src/main/kotlin/domain/card/Cards.kt
> +    fun checkBlackJack(): Boolean =
사소하지만, 
check라는 함수명은 리턴을 기대하지는 않을수도 있을거같아요!
보통 Boolean을 리턴할때 is, has 와 같은 접두사를 자주 사용하곤 합니다!

2023-03-13 13:52 UTC, merged