[글로] 2단계 블랙잭 제출합니다.
woowacourse/kotlin-blackjack pull request #42
Opened 2023-03-09 13:24 UTC by ippnsj

안녕하세요 리뷰어님~! 😄
이전 단계에서 이전에 DTO였던 클래스들로 뷰에 넘겨줄 때 데이터를 감싸주라고 하셔서 뷰에서 필요한 값들을 감싸서 전달하게 하였습니다! 
다른 크루들로부터 리뷰어님이 컨트롤러 테스트가 필요하다고 생각하신다는 것을 들었습니다. 그래서 제 나름 컨트롤러 테스트가 왜 필요할까 생각해 보았을 때, 컨트롤러가 실행해야 하는 로직을 실행하지 않는 것을 잡기 위해서 필요할 수 있다고 생각했고, 이것을 테스트하는 것을 중심으로 컨트롤러 테스트 코드를 짜보았습니다! 🤗
제가 듣기로 리뷰어님께서는 컨트롤러에서 비즈니스 로직을 수행할 수 있어서 테스트가 필요하다고 하셨다는데 지금까지 컨트롤러는 도메인이 아니기 때문에 비즈니스 로직을 수행하면 안 된다고 생각하고 있었어서 약간 혼란스럽습니다...😵‍💫😭
리뷰어님이 생각하시는 컨트롤러에서 수행해야할 비즈니스 로직이 무엇인지 궁금합니다~! 🤓

2023-03-10 12:42 UTC, galcyurio requested changes
2단계 미션 잘 진행해주셨네요.
Controller에 대한 단위테스트를 작성하는게 어려웠을텐데 잘 작성해주셨습니다.
피드백을 남겨두었으니 확인 후 다시 요청해주세요!

2023-03-10 12:42 UTC, galcyurio commented on src/main/kotlin/blackjack/domain/participant/Participants.kt
> +    fun getFirstOpenCards(): List<ParticipantCards> = listOf(ParticipantCards(dealer.name, dealer.getFirstOpenCards())) + bettingPlayers.getFirstOpenCards()
한 줄이 너무 길어지는 경우에는 expression body 대신에 지역변수로 선언하는걸 추천드려요.

2023-03-10 12:42 UTC, galcyurio commented on src/main/kotlin/blackjack/domain/participant/Participants.kt
> +    }
`block` 이라는 이름을 통해 어떤 역할인지를 알 수가 없습니다.
콜백함수 또한 분명한 역할이 있어야 합니다.

domain layer 에서는 ui layer에 대해서 알지 못해야 하므로 철저하게 domain의 입장에서 외부에 드러내기 위한 콜백함수를 선언해주세요.
예를 들면 `onDealerHit()`과 같습니다.

2023-03-10 12:42 UTC, galcyurio commented on src/main/kotlin/blackjack/domain/participant/Participants.kt
> +        block(false)
호출하는 곳을 보니 if문으로 분기하고 있어서 마지막 콜백 함수 호출은 불필요해보입니다.

2023-03-10 12:42 UTC, galcyurio commented on src/main/kotlin/blackjack/domain/participant/BettingPlayer.kt
> +class BettingPlayer(private val player: Player, val money: Int) {
Player와 BettingPlayer가 나누어진 이유는 무엇인가요?
객체지향적으로 생각했을 때, player가 player를 가지고 있다는게 조금 어색하게 느껴져요.

2023-03-10 12:42 UTC, galcyurio commented on src/main/kotlin/blackjack/view/Console.kt
> +    }
아래와 같이 별도의 클래스로 분리할 수도 있습니다.

```kotlin
number.toPresentation().text
```

```kotlin
enum class CardNumberModel(val text: String) {
    ACE("A"),
    TWO("2"),
    THREE("3"),
    FOUR("4"),
    FIVE("5"),
    SIX("6"),
    SEVEN("7"),
    EIGHT("8"),
    NINE("9"),
    TEN("10"),
    JACK("J"),
    QUEEN("Q"),
    KING("K"),
}

fun CardNumber.toPresentation(): CardNumberModel = when (this) {
    CardNumber.ACE -> CardNumberModel.ACE
    CardNumber.TWO -> CardNumberModel.TWO
    CardNumber.THREE -> CardNumberModel.THREE
    CardNumber.FOUR -> CardNumberModel.FOUR
    CardNumber.FIVE -> CardNumberModel.FIVE
    CardNumber.SIX -> CardNumberModel.SIX
    CardNumber.SEVEN -> CardNumberModel.SEVEN
    CardNumber.EIGHT -> CardNumberModel.EIGHT
    CardNumber.NINE -> CardNumberModel.NINE
    CardNumber.TEN -> CardNumberModel.TEN
    CardNumber.JACK -> CardNumberModel.JACK
    CardNumber.QUEEN -> CardNumberModel.QUEEN
    CardNumber.KING -> CardNumberModel.KING
}
```

2023-03-10 12:42 UTC, galcyurio commented on src/test/kotlin/blackjack/controller/BlackJackControllerTest.kt
> +    }
junit5의 soft assertion 기능을 쓸 때, 너무 길어지는 경우 assertj의 soft assertion 기능을 사용해보세요.

```kotlin
@Test
fun `참여자들이 처음 공개하는 카드 확인`() {
    val soft = SoftAssertions()

    val expected0 = ParticipantCards("딜러", listOf(Card(CardNumber.JACK, Suit.SPADE)))
    soft.assertThat(outputView.firstOpenCards[0]).isEqualTo(expected0)

    val expected1 = ParticipantCards("부나", listOf(Card(CardNumber.QUEEN, Suit.DIAMOND), Card(CardNumber.KING, Suit.DIAMOND)))
    soft.assertThat(outputView.firstOpenCards[1]).isEqualTo(expected1)

    val expected2 = ParticipantCards("글로", listOf(Card(CardNumber.KING, Suit.HEART), Card(CardNumber.ACE, Suit.HEART)))
    soft.assertThat(outputView.firstOpenCards[2]).isEqualTo(expected2)

    val expected3 = ParticipantCards("반달", listOf(Card(CardNumber.EIGHT, Suit.CLOVER), Card(CardNumber.JACK, Suit.CLOVER)))
    soft.assertThat(outputView.firstOpenCards[3]).isEqualTo(expected3)

    val expected4 = ParticipantCards("제이슨", listOf(Card(CardNumber.JACK, Suit.HEART), Card(CardNumber.NINE, Suit.HEART)))
    soft.assertThat(outputView.firstOpenCards[4]).isEqualTo(expected4)
}
```

2023-03-10 12:42 UTC, galcyurio commented on src/test/kotlin/blackjack/controller/BlackJackControllerTest.kt
> +class BlackJackControllerTest {
제 기준에서 로직은 크게 2개로 나눌 수 있습니다.

- ui logic
- business logic

여기서 business logic은 세부적으로 아래와 같이 나눌 수 있습니다.

- presentation logic: Controller, Presenter, ViewModel
- domain logic: blackjack과 같이 해당 도메인과 밀접한 로직
- data logic: API를 요청하거나 로컬 저장소에 접근하는 로직

Controller에는 presentation logic이 존재합니다.
MVC 패턴으로 이야기하자면 Model을 호출하고 View에 전달하는 로직입니다.
이 로직이 잘못되는 경우 프로그램도 잘못 동작하게 되므로 마찬가지로 테스트되어야 합니다.

-----

안드로이드에서는 특히나 presentation logic을 domain logic보다 많이 작성하게 되므로 더 중요합니다.

2023-03-11 11:43 UTC, ippnsj commented on src/main/kotlin/blackjack/domain/participant/BettingPlayer.kt
> +class BettingPlayer(private val player: Player, val money: Int) {
게임에 참여하지 않은 유저와 게임에 참여한 유저로 나누고 싶었는데 Player라고 하면 좀 이상할 것 같네요!
플레이어 대신 유저로 바꾸면 괜찮을까요?

2023-03-11 11:44 UTC, ippnsj commented on src/main/kotlin/blackjack/domain/participant/BettingPlayer.kt
> +class BettingPlayer(private val player: Player, val money: Int) {
근데 이렇게 되면 유저가 Participant를 상속하는게 이상해지겠네욤ㅠㅠ

2023-03-12 12:37 UTC, galcyurio requested changes
피드백 잘 반영해주셨네요 👍 
마지막으로 몇 가지만 개선해보고 끝내면 좋겠습니다.
수정 후 다시 요청해주세요!

2023-03-12 12:37 UTC, galcyurio commented on src/main/kotlin/blackjack/view/Console.kt
> +    }.text
mapper 함수들은 해당 클래스가 선언된 곳에 top-level로 선언해주세요.
지금은 한 곳에서만 쓰이지만 조금만 큰 프로젝트를 진행해도 여러 곳에서 접근할 필요가 생깁니다.

2023-03-12 12:37 UTC, galcyurio commented on src/main/kotlin/blackjack/domain/participant/PlayerInfo.kt
> +data class PlayerInfo(val name: String, val money: Int, val askDraw: (String) -> Boolean = { true })
Player라는 객체가 해당 정보를 가지고 있어야 합니다.
PlayerInfo를 선언하는 대신 Player에서 해당 필드들을 가지도록 해보세요.

2023-03-12 12:37 UTC, galcyurio commented on src/main/kotlin/blackjack/domain/participant/BettingPlayer.kt
> +class BettingPlayer(private val player: Player, val money: Int) {
그렇다면 BettingPlayers라는 객체를 만들고 게임에 참여한 Player들만 가지도록 만들어보면 어떨까요?

2023-03-12 17:14 UTC, ippnsj commented on src/main/kotlin/blackjack/domain/participant/BettingPlayer.kt
> +class BettingPlayer(private val player: Player, val money: Int) {
좋아용~!😄

2023-03-13 03:19 UTC, galcyurio approved these changes
상태 패턴으로 잘 리팩터링해주셨네요 👍 
몇 가지 피드백을 남겨두었으니 확인해주세요.
수정할 것들이 많지 않아 바로 merge하도록 하겠습니다.
지금까지 블랙잭 미션 고생하셨습니다 👏

2023-03-13 03:19 UTC, galcyurio commented on src/main/kotlin/blackjack/domain/participant/BettingPlayers.kt
> +        get() = _players.toList()
List 자체는 읽기만 하고 변경하지 않기 때문에 `_` 없이 아래와 같이 작성하실 수 있습니다.

```kotlin
class BettingPlayers(players: List<Player>, private val money: Map<Player, Int>) {
    val players: List<Player> = players.toList()
```

2023-03-13 03:19 UTC, galcyurio commented on src/main/kotlin/blackjack/domain/state/State.kt
> +}
불변 + 상태 패턴으로 모두 리팩터링하셨군요 👍

2023-03-13 03:19 UTC, galcyurio commented on src/main/kotlin/blackjack/view/Console.kt
> +    }.text
최초에 코멘트했던 것처럼 CardNumberModel.kt 파일에 작성해야한다는 의미였습니다.

```kotlin
enum class CardNumberModel(val text: String) {
    ACE("A"),
    TWO("2"),
    THREE("3"),
    FOUR("4"),
    FIVE("5"),
    SIX("6"),
    SEVEN("7"),
    EIGHT("8"),
    NINE("9"),
    TEN("10"),
    JACK("J"),
    QUEEN("Q"),
    KING("K"),
}

fun CardNumber.toPresentation(): CardNumberModel = when (this) {
    CardNumber.ACE -> CardNumberModel.ACE
    CardNumber.TWO -> CardNumberModel.TWO
    CardNumber.THREE -> CardNumberModel.THREE
    CardNumber.FOUR -> CardNumberModel.FOUR
    CardNumber.FIVE -> CardNumberModel.FIVE
    CardNumber.SIX -> CardNumberModel.SIX
    CardNumber.SEVEN -> CardNumberModel.SEVEN
    CardNumber.EIGHT -> CardNumberModel.EIGHT
    CardNumber.NINE -> CardNumberModel.NINE
    CardNumber.TEN -> CardNumberModel.TEN
    CardNumber.JACK -> CardNumberModel.JACK
    CardNumber.QUEEN -> CardNumberModel.QUEEN
    CardNumber.KING -> CardNumberModel.KING
}
```

2023-03-13 03:19 UTC, merged