[써니] 2단계 블랙잭 제출합니다.
woowacourse/kotlin-blackjack pull request #49
Opened 2023-03-10 09:01 UTC by inseonyun

안녕하세요 리뷰어님 지난 1단계 리뷰 너무 감사합니다.
덕분에 성장하고 코드 작성에 많은 고민을 할 수 있어 좋았습니다.
많이 부족하지만 2단계도 잘 부탁드립니다! 😊

2023-03-10 15:26 UTC, laco-dev requested changes
2단계 미션 잘 해주셨습니다.

점차 발전하는 모습이 보기 좋게 느껴졌습니다.
공통으로 사용하는 부분에 있어서도 여러번 시도 하면서 익숙해지실 것 같습니다.

딜러와 플레이어 모두 수익금이라는 공통된 목표를 구현하고 있기 때문에 관련된 피드백을 몇가지 남겨보았습니다.

충분히 고민후 도전 해보세요. 🙏🏻

2023-03-10 15:26 UTC, laco-dev commented on src/main/kotlin/model/Player.kt
> +    }
수익금은 딜러와 플레이어 모두에게 필요한 기능이 아닐까요?
```
수익금을 반환한다
1. 딜러 : 참가자의 손해만큼 수익금 계산
2. 참가자 : 상대방과 비교해서 수익금 계산
```
그렇다면 우리가 연습한 것과 같이 추상 함수로 구현을 해 볼 수 있지 않을까요?

아래 코멘트를 이어서 봐주세요 🙏🏻

2023-03-10 15:26 UTC, laco-dev commented on src/main/kotlin/model/Participant.kt
> +        return Result.LOSE
참가자에게 요구하는 것은 게임의 결과라기 보다는 수익금이 목표라고 생각합니다.
그 과정에서 게임의 결과는 수익금을 계산하기 위한 절차로 볼 수 있는데요.

아래와 같은 시그니처로 구현이 가능할 것 같아요.
```kotlin
abstract class Participant {
   // 딜러의 수익금 계산 방식
   // 플레이어의 수익금 계산 방식
   abstract fun getProfit(other: Participant): Profit
}

```

딜러의 경우 모든 플레이어와 합친 것을 수익금이라고 생각했기 때문에 하나로 합치지 못한 것으로 보이는데요.

전부 합치는건 모든 참가자와 승부하는 개념이고, 각각의 참가자와 승부하는 것에 있어서랑은 다르게 해석해 볼 수 있겠습니다.

다시 말하면 모든 참가자들과 승부한 수익금들의 합계가 곧 전체 수익금이 되겠죠?

2023-03-10 15:26 UTC, laco-dev commented on src/main/kotlin/view/OutputView.kt
> +        private const val MESSAGE_PLAYER_PROFIT_RESULT = "%s: %d"
딜러가 "딜러"라는 이름을 가지고 있기 때문에 두개가 나눠질 필요가 없지 않나요?

2023-03-10 15:26 UTC, laco-dev commented on src/test/kotlin/blackjack/model/DealerTest.kt
> +        assertThat(dealer.cards.cards).isEqualTo(expected)
참가자가 카드를 생성자로 가지는 방법에서 안에서 초기화 하는 것으로 바뀐 이유가 있을까요?
카드를 준비하기 위해 다소 불편한 방법(덱)을 사용하는 것처럼 느껴집니다.

2023-03-10 15:26 UTC, laco-dev commented on src/test/kotlin/blackjack/model/PlayerTest.kt
> +        assertThat(player.getGameResult(dealer)).isEqualTo(Result.DRAW)
앞선 의견처럼 딜러와의 승부 자체가 중요한 것이 아닌, 얼만큼의 수익금을 얻었는가의 관점으로 바라본다면 관련된 테스트 코드도 같이 수정이 되어야 할 수 있어요.

```
1000원의 배팅으로 딜러와 플레이어 모두 블랙잭이라면 1000원의 수익을 가진다
1000원의 배팅으로 딜러가 블랙잭, 플레이어가 스테이라면 -1000원의 수익을 가진다
1000원의 배팅으로 ...
```

2023-03-12 07:09 UTC, inseonyun commented on src/test/kotlin/blackjack/model/DealerTest.kt
> +        assertThat(dealer.cards.cards).isEqualTo(expected)
요구사항 중 하나인 ```3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.```를 충족하기 위해 
2단계 주요 기능 목록인 베팅 금액을 어떻게 관리할지 고민해보았습니다.
기존 구조에서 추가적으로 player와 Money를 생성자로 갖는 BettingPlayer를 구현하여 기능 구현을 해 나갈지,
아니면 기존 구조에 변화만 줄지 고민하였습니다.
고민 중 Dealer와 Player 모두 Participant의 Cards를 사용할뿐 각각의 참가자(dealer, player)가 지닌 cards 프로퍼티는 Participant에 접근을 해 사용하다보니 필요성이 없다 생각했고, Participant에 생성자가아닌  cards 프로퍼티를 둬서 생성, 관리 하는 것이 가능하다는 것을 알 게 되어 해당 방법을 택하게 되었습니다.  
물론 이러한 방법이 객체 지향에 맞는 선택일지 의문이 들기도 해서 이와 같은 시도에 리뷰를 받고자 도전해보았습니다!

리뷰어님의 말씀대로 ```카드를 준비하기 위해 다소 불편한 방법(덱)을 사용하는 것처럼 느껴집니다.```을 느끼긴 했으나 다른 한 편으로는 '딜러와 플레이어가 생성 될 때 카드를 함께 줘서 생성할 필요가 있을까?' 라는 생각이 들었습니다.
이에 대해서는 어떻게 생각하시는지 리뷰어님의 의견 궁금합니다!

2023-03-12 15:28 UTC, laco-dev requested changes
피드백 반영 잘 해주셨습니다.

전체적으로 다시 확인하면서, 규칙이 다소 잘못 정의된 부분이 있어서 관련된 피드백을 남겨드렸습니다.
그 외에도 개선해 볼 만한 내용을 몇 가지 남겨드렸으니 확인 부탁드립니다.

2023-03-12 15:28 UTC, laco-dev commented on src/test/kotlin/blackjack/domain/CardGameTest.kt
> +    fun `딜러와 플레이어가 블랙잭인 경우 딜러와 플레이어 수익은 0이다`() {
> 딜러와 플레이어가 모두 동시에 블랙잭인 경우 플레이어는 베팅한 금액을 돌려받는다.

베팅한 금액과 당첨금을 합쳐서 수익을 계산하는 것이 아닌
베팅금과 수익은 따로 봐야 합니다.

즉 만원을 베팅해서 위 경우에 해당된다면 수익은 만원입니다.

2023-03-12 15:28 UTC, laco-dev commented on src/main/kotlin/model/CardGameResult.kt
> +}
수익금에 대한 배율은 단순히 결과로 계산되지 않고,
비교하는 상대방의 카드 상태를 이용해 같이 계산이 됩니다.
즉 두명 모두 블랙잭이라면 1.5배가 아닌 1배로 계산이 됩니다.

게임의 결과라고 표현하는 대신 EarningRate라는 표현을 사용해보면 어떨까요?

2023-03-12 15:28 UTC, laco-dev commented on src/test/kotlin/blackjack/model/DealerTest.kt
> +        assertThat(dealer.cards.cards).isEqualTo(expected)
> 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

프로그램을 구현하면서, 설계에 따라 3개 이상의 변수가 만들어 질 수도 있습니다.
반드시 모든 조건을 지켜나가야만 좋은 설계인 것은 아닙니다.
3가지 이상을 썼을 때 오히려 더욱 좋은 구조가 된다면, 물론 사용하는 것이 좋습니다.

저는 앞서 사용하신 내용이 잘못되었다고 하지 않고, 하나의 "불편한 방법"이라고 알려 드렸는데요.
말씀하신대로 딜러와 플레이어가 생성될 때 함께 카드를 주지 않는것도 방법 중 하나입니다.

그리고 설계를 하면서 여러가지 방법중 하나를 선택하는 순간이 자주 옵니다.
트레이드 오프라고 하는 영역에서, 각각의 방법이 어떠한 장단점을 가지는지를 비교하고, 결과적으로 선택을 하게 됩니다.

가령 아래와 같은 기능이 추가된다면 지금의 구조는 귀찮은 상황이 오게 될 것 같습니다.
이런 기능이 전혀 없을것이라고는 장담할 수 없겠죠. 개발을 하다보면 언제나 요구사항은 튀어나오니까요.

```kotlin
fun `플레이어가 52장의 카드를 가지고 있다면, 추가로 카드를 뽑을 수 없다`() {
   // given
   val player: Player
   val cardDeck: CardDeck = CardDeck.All
   // 대충 필요한 카드를 항상 drawCard 해야 함
   repeat(52) {
      player.drawCard(cardDeck)
   }
   // when
   player.drawCard(Card)
   
   // then
   assertThat(...)
}

fun `플레이어가 스페이드 모양의 카드를 모두 가지고 있다면, ...`
```

2023-03-13 05:35 UTC, inseonyun commented on src/test/kotlin/blackjack/domain/CardGameTest.kt
> +    fun `딜러와 플레이어가 블랙잭인 경우 딜러와 플레이어 수익은 0이다`() {
세상에,,,제가 딜러, 플레이어 수익 계산 룰을 잘못 이해하고 있었군요...
'베팅금과 수익은 따로 봐야 합니다.'가 수익 계산에 가장 큰 핵심이네요!

EarningRate는 다음과 같이 바꿨습니다!
+ 블랙잭 : 1.5배 
+ 이기거나 딜러와 플레이어 BLACKJACK : 1배
+ 비긴 경우: 0배
+ 진 경우: -1배

감사합니다 : )

2023-03-13 08:57 UTC, inseonyun commented
1. drawCard()라는 함수가 참가자를 파라미터로 받을 필요가 있었을까요?
참가자들을 생성자로 받아서 가지고 있기 때문에, 가지고있는 참가자들을 순회하며 카드를 뽑아도 될 것 같아요.

2. 외부에서 Result가 어떤 결과인지 알고싶을까요??
수익금을 계산하기 위해 사용되는 과정이 아닐까요?

3. 참가자가 카드를 생성자로 가지는 방법에서 안에서 초기화 하는 것으로 바뀐 이유가 있을까요?
카드를 준비하기 위해 다소 불편한 방법(덱)을 사용하는 것처럼 느껴집니다.

해당 코멘트들의 내용, 이번 요청 후 있을 피드백 반영 후 추후 재요청 하겠습니다...!!
미션이 곧 마감이라 남은 내용은 반영을 못했지만 리뷰 요청합니다...
죄송합니다 ㅠㅠㅠ

2023-03-13 13:24 UTC, laco-dev commented on src/test/kotlin/blackjack/domain/CardGameTest.kt
> +    fun `딜러와 플레이어가 블랙잭인 경우 딜러와 플레이어 수익은 0이다`() {
이건 저도 착각했네요.

둘다 블랙잭이면 돈을 그대로 돌려받으니 수익은 0원이 맞습니다

2023-03-13 13:44 UTC, laco-dev requested changes
피드백 반영하느라 고생 많으셨습니다.

수익금액 규칙을 저도 잘못 이해한 부분이 있어서, 댓글 추가로 남겨두었습니다.
마지막 단계인 만큼 추가로 개선해볼만한 내용을 남겨보았습니다.

2023-03-13 13:44 UTC, laco-dev commented on src/main/kotlin/domain/CardGame.kt
> +    fun drawCard(status: (Participant) -> Unit) {
drawCard()가 하는 역할이 모든 참가자와 딜러가 카드를 뽑는 것인데요.
인터페이스의 이름과 잘 매칭이 안되지 않을까요!?

게임을 시작한다는 의미로 사용하고, 게임의 결과를 반환하도록 만들어 보면 어떨까요?

```kotlin
fun start(...) : ParticipantsProfitGameResult { ... }
```

2023-03-13 23:30 UTC, laco-dev approved these changes
블랙잭 미션동안 고생 많으셧습니다.

그동안 경험하신 것들이 무조건 맞다고 생각하기 보다는, 자기만의 이유를 만들어서 발전시켜 나가시면 좋겠습니다.

2023-03-13 23:31 UTC, merged