[코비] 2단계 블랙잭 제출합니다.
woowacourse/kotlin-blackjack pull request #50
Opened 2023-03-10 13:13 UTC by rhkrwngud445

리뷰 감사드립니다! 이전 피드백 반영하였습니다! 

다만 [링크](https://github.com/woowacourse/kotlin-blackjack/pull/17#discussion_r1127802584) 해당 피드백에서 "다른 인스턴스를 만들 수 있는 구조"를 잘 이해 못하였습니다😥
어떻게 접근해야 할지 참고할 예시나 키워드 부탁드려도 괜찮으실까요..?!

2023-03-11 17:00 UTC, malibinYun requested changes
리뷰가 늦어져서 정말 죄송합니다 😥
2단계 미션 고생 많으셨어요 :)

여러 고민점에 코멘트 달아두었으니, 확인해보세요!
피드백 반영 후 다시 리뷰 요청부탁드려요 :)

2023-03-11 17:05 UTC, malibinYun commented
> 다만 https://github.com/woowacourse/kotlin-blackjack/pull/17#discussion_r1127802584 해당 피드백에서 "다른 인스턴스를 만들 수 있는 구조"를 잘 이해 못하였습니다😥
어떻게 접근해야 할지 참고할 예시나 키워드 부탁드려도 괜찮으실까요..?!

Card.getAllCard() 호출하고, 해당 카드를 반환 받은 곳에서 카드를 받으면, 동일한 카드에 대해 동일한 인스턴스를 가지고 있겠지요 :)
하지만, 외부에서 Card.getAllCard()를 거치지 않고 Card(...) 를 호출함으로써 생성할 수 있습니다. 

아래 코드에서 card1과 card2의 인스턴스는 동일할까요?
```kotlin
val card1 = Card(Shape.CLUBS, CardValue.ACE)
val card2 = Card(Shape.CLUBS, CardValue.ACE)
```

2023-03-13 04:55 UTC, rhkrwngud445 commented on src/main/kotlin/domain/BlackjackGame.kt
> +    fun calculateDealerRewards(playerResults: List<Int>): Int = playerResults.sum() * -1
Inferred Type일 때 super 혹은 interface 형태로 리턴되지 않기 때문에, 제 코드를 직접 조작하지 않는 이상 외부에서 코드를 조작하기 어렵습니다.
또한 코드 내부로 들어가서 타입을 확인을 해주어야 하는 비용이 발생하기 때문에, 타입을 명시하는 것이 좋겠네요!!

2023-03-13 06:49 UTC, rhkrwngud445 commented on src/main/kotlin/domain/gamer/cards/Cards.kt
>          calculateCardSum() == CARD_SUM_MAX_VALUE && cards.size == START_DECK_CARD_COUNT
프로퍼티로 둘 생각을 못했었네요.. 위의 덱[리뷰링크](https://github.com/woowacourse/kotlin-blackjack/pull/50#discussion_r1133118784)와 같이 프로퍼티로 두어 외부적으로 불변한 객체를 생성할 수 있다는 것을 간과했었습니다..😭

2023-03-13 11:13 UTC, rhkrwngud445 commented on src/test/kotlin/domain/deck/DeckTest.kt
> +        assertThat(deck.giveCard()).isEqualTo(Card(Shape.SPADE, SEVEN))
assertAll은 이전 테스트가 틀렸어도 어디서 값이 또 다른지 알 수 있습니다! 테스트 수가 많아지면 효율적일 것 같습니다!

2023-03-13 11:54 UTC, rhkrwngud445 commented
Card에서 많이 막혔었는데, 친절히 설명해주셔서 수업때 어떤 부분이 부족했는지 짚어 볼 수 있었습니다!
리뷰 감사드립니다!!

2023-03-13 15:09 UTC, malibinYun approved these changes
2단계 미션 고생 많으셨어요!!
미션 기한이 지나 아쉽게도 바로 머지해야해요 ㅠ_ㅠ
다음 미션에는 기한을 꼭 지켜서 리뷰 받으시길 바라요 😥

그래도 저와 함께 미션을 진행하면서 고민했던 것들이 미래에 도움이 되셨으면 좋겠어요!!
다른 미션들도 잘 해내시길 응원할게요! 💪🔥

2023-03-13 15:09 UTC, merged