[블랙잭] 예니 1단계 미션 제출합니다.
woowacourse/kotlin-blackjack pull request #66
Opened 2024-03-08 04:49 UTC by JoYehyun99

안녕하세요! 잘 부탁드립니다 🙃

2024-03-09 05:13 UTC, vagabond95 requested changes
안녕하세요~! 
블랙잭 미션동안 잘 부탁드립니다 :)

모델의 역할과 연결관계에 대해 많은 고민이 느껴지는 코드였습니다 👍 
전반적으로 가독성도 뛰어났어요.

고민해볼만한 부분에 대해 코멘트 남겼는데 확인 부탁드릴게요~!

2024-03-09 05:13 UTC, vagabond95 commented on src/main/kotlin/blackjack/model/BlackjackGame.kt
> +        displayParticipantsStatus: (Participant) -> Unit,
BlackjackGame 은 model 이므로, display 가 될거라는 사실은 알 수 없지 않을까요~?

2024-03-09 05:13 UTC, vagabond95 commented on src/main/kotlin/blackjack/model/BlackjackGame.kt
> +        askForPlayerAction: (name: ParticipantName) -> Boolean,
askForPlayerAction 라는 네이밍을 봤을 때, 리턴되는 boolean 값이 무엇을 의미하는지 알기 어려울 것 같아요.

2024-03-09 05:13 UTC, vagabond95 commented on src/main/kotlin/blackjack/model/BlackjackGame.kt
> +    fun calculateResult(): Map<Participant, WinningState> {
calculateResult 함수는 public 이므로 언제든 호출이 가능한데요, play 하지 않고 먼저 호출할 경우 의도하지 않은 결과가 리턴될 것 같아요.

외부에서는 함수를 어떤 순서로 호출할지 알 수 없으므로
특정 함수들의 호출 순서가 보장되어야한다면, 리펙토링이 필요할 것 같습니다!

2024-03-09 05:13 UTC, vagabond95 commented on src/main/kotlin/blackjack/model/BlackjackGame.kt
> +        val dealerWinCount = outcomes.values.count { it.wins == 0 && it.losses == 1 }
현재의 조건식으로 딜러의 승리/패배를 판단하기에는 버그를 유발할 가능성이 있어보여요.
예를들어 만약 아래와 같은 상태라면, 어떻게 카운트가 되어야할까요?
```suggestion
        val dealerWinCount = outcomes.values.count { it.wins == 1 && it.losses == 2 }
```

2024-03-09 05:13 UTC, vagabond95 commented on src/main/kotlin/blackjack/model/BlackjackGame.kt
> +    private fun getPlayersWinningState(
WinningState 를 구하는 로직들은 dealer 와 개별 player 를 모두 알고 있는 
`participants` 에서 스스로 처리할 수 있을 것 같습니다!

2024-03-11 11:48 UTC, JoYehyun99 commented
전반적으로 코드 구조를 많이 수정했습니다...! 🥹
- `Player`와 `Dealer`, `Participants` 에서 게임 진행, 게임 결과 반환 로직을 옮기면서 `BlackjackGame`  클래스를 제거했습니다! 
-  원래 `Participants`는 `BlackjackGame`  클래스에 넘겨주기 위해서 생성했던 것인데, `BlackjackGame`  클래스가 제거되고, 게임 결과를 계산하는 로직을 넣으면서 어떤 책임을 가지고 있는 건지 애매해진 것 같다는 생각이 들었는데 어떻게 생각하시는지 궁금합니다!
- test 코드에서 test fixture들을 편하게 만들기 위해 여러 메서드들을 사용했는데, 이러한 메서드들을 하나의 유틸 파일로 분리해야 하는 것인지 궁금합니다!

2024-03-12 01:20 UTC, vagabond95 commented
> Participants 의 역할

Participants 는 players 와 dealer 를 상태로 가지고 있으므로, 해당 상태들을 이용하여 스스로 처리할 수 있는 일을 수행하면 된다고 생각하는데요, 현 구현상으로는 기준에 적합한 것 같습니다 👍 

> 테스트 코드 분리

테스트 코드에만 사용될 수 있도록 한다면, 분리되어도 좋다고 생각합니다 :)

2024-03-12 01:39 UTC, vagabond95 requested changes
이전보다 함수/클래스의 역할이 훨씬 명확해진 것 같습니다 👍 

조금 더 고민해볼만한 내용에 대해 코멘트 남겼는데, 확인 부탁드릴게요~!

2024-03-12 01:39 UTC, vagabond95 commented on src/main/kotlin/blackjack/model/State.kt
> +        fun determineInitialGameState(
Hit 에서 처리해주신 것처럼, 상태가 스스로 다음 상태를 결정하도록 리펙토링해볼 수 있을까요~?

2024-03-12 01:39 UTC, vagabond95 commented on src/main/kotlin/blackjack/controller/BlackjackController.kt
> +            Dealer(state = State.determineInitialGameState(Hand(List(INITIAL_DISTRIBUTE_COUNT) { deck.pick() })))
코드를 단계별로 나눠보면 좋을 것 같아요.
현재 코드는 가독성이 조금 떨어지는 것 같습니다 😢

2024-03-12 01:39 UTC, vagabond95 commented on src/main/kotlin/blackjack/model/CardDeckGenerator.kt
> +    fun generate(): CardDeck = CardDeck
deck 재사용 시도 👍 
그런데, shuffled 된 deck 을 저장하고 이를 그대로 리턴할 경우 결과적으로는 매번 똑같이 shuffled 된 deck 이 리턴될 것 같아요.

shuffled 해주는 순서를 변경해보면 어떨까요?

2024-03-12 14:35 UTC, vagabond95 approved these changes
코멘트 내용을 정말 빠르게 반영해주셨었네요 ㅎㅎ

1단계는 여기서 마무리하고 다음 단계에서 블랙잭 상태를 더 잘관리 할 방법은 없을지
같이 고민해보면 좋을 것 같습니다. 고생 많으셨습니다~!

2024-03-12 14:36 UTC, merged