[블랙잭] 채드 1단계 미션 제출합니다.
woowacourse/kotlin-blackjack pull request #78
Opened 2024-03-08 08:04 UTC by dpcks0509

안녕하세요 안드로이기 6기 채드입니다!
부족한 실력이지만 리뷰 잘 부탁드립니다!

2024-03-08 16:27 UTC, Gyuil-Hwnag requested changes
채드 안녕하세요!
이번 미션을 함께하게 된 두루라고 합니다. 잘부탁드립니다!

해당 미션 구현 고생 많으셨습니다!

전반적으로 객체에서 책임을 져야 하는 기능들에 대해서 고민을 해보면 좋을 것 같다는 생각이 들었습니다🤔
고민해보시면 좋을만한 내용들 코멘트를 달았으니 확인해주시면 감사하겠습니다.

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 
화이팅입니다💪

2024-03-08 16:27 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        }
딜러의 상태를 체크하는 것이 과연 Controller 에서 가지고 있어야 하는 책임인지에 대해서 고민해보면 좋을 것 같습니다!!🤔

2024-03-08 16:27 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +            }
drawOrNot 함수와 drawOrNot 변수는 물론 다르지만 네이밍이 같음으로서 자칫 혼란을 야기할 수 있겠다는 생각이 듭니다🥲

2024-03-08 16:27 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/card/Card.kt
> +            }
toString()을 return "$number$shape"처럼 정의한 것은 좋은데, number & shape에 대한 분기 내용이 Card에서 책임을 지고 있어야 하는지는 고민해보면 좋을 것 같습니다!🤔

2024-03-08 16:27 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/card/Deck.kt
> +object Deck {
Deck을 object 키워드로 정의하신 이유가 있을까요??

2024-03-08 16:27 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/game/ScoreCalculation.kt
> +    }
요구사항에 맞게 에이스 카드에 대한 로직에 대해서 고민해보시면 좋을 것 같다는 생각이 듭니다!!💪
`에이스 카드가 포함되어 있을 때, 카드들의 점수 합계가 11점보다 낮다면 보너스 점수 10점을 획득한다.`

2024-03-08 16:27 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/game/ScoreCalculation.kt
> +object ScoreCalculation {
해당 객체의 경우 hand 에 대한 계산만을 담당하고 있는 객체 같은데, 해당 책임을 hand 에서 가지고 기능을 하도록 해도 될 것 같다는 생각이 듭니다!!

2024-03-08 16:27 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/game/State.kt
> +        data object Hit : Running
유저가 카드를 뽑지 않는 경우도 존재를 하는데, 이에 대해서도 추가를 하면 추후에 조건이 바뀌었을 때 좀더 유연하게 적용을 할 수 있을것 같다는 생각이 듭니다🤔

2024-03-08 16:27 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/player/Dealer.kt
> +        return ScoreCalculation.calculate(hand) <= 16
ScoreCalculation에서 담당하고 있는 기능들이 hand로 수정이 된다면, 해당 내용도 수정이 될 수 있을 것 같다는 생각이 듭니다!!

추가적으로 조건의 경우 하드 코딩되어 있는 내용을 상수로 관리를 해봐도 좋을 것 같다는 생각이 듭니다🤔

2024-03-08 16:27 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/player/Player.kt
> +class Player(val name: String, val hand: Hand) {
해당 내용도 살펴보시면 좋을 것 같습니다!
![스크린샷 2024-03-09 01 19 07](https://github.com/woowacourse/kotlin-blackjack/assets/84956038/9397428b-a7dc-4460-838c-30cd8dd5d89e)

2024-03-08 16:27 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/view/InputView.kt
> +}
inputView 에서 담당하고 있어야 할 내용들이 Controller에 있어서, 해당 내용들도 수정해시면 좋을 것 같습니다!💪

2024-03-08 16:27 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/view/ProgressView.kt
> +            Finished.Bust -> " (Bust)"
공통으로 사용되고 있는 하드코딩된 값들을 상수값으로 관리해보는 것도 좋을 것 같다는 생각이 듭니다!

2024-03-08 16:27 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/view/ProgressView.kt
> +        }
fun showPlayerHand(player: Player)와 같은 기능을 하는 것으로 보이는데, 하나의 함수로 통합할 수 있다면 통합해보는 것도 좋을 것 같다는 생각이 듭니다!💪

2024-03-08 16:27 UTC, Gyuil-Hwnag commented on src/test/kotlin/blackjack/CardTest.kt
> +}
테스트 코드에 대한 전반적인 코멘트 입니다!!

테스트 코드의 경우 어떤 테스트인지 확실하게 알 수 있게 네이밍을 정해주는 것도 좋은 것 같습니다!

~~~kotlin
    @Test
    fun `자동차가 1칸 이동하면 거리는 1이다`() {
        // given
        val myCar = Car("Duru")
        // when
        myCar.move(1)
        // result 
        assertThat(myCar.distance).isEqualTo(1)
    }
~~~

2024-03-08 16:27 UTC, Gyuil-Hwnag commented on src/test/kotlin/blackjack/DealerTest.kt
> +    }
Deck 객체가 object로 생성됨으로 인하여 해당 내용이 추가되었다는 생각이 드는데, 어떻게 수정을 하는 것이 좋을지 고민해보면 좋을 것 같습니다!🤔

2024-03-08 16:27 UTC, Gyuil-Hwnag commented on src/test/kotlin/blackjack/DealerTest.kt
> +    }
테스트 코드에는 test fixture 라는 개념이 존재하는데 내용을 살펴보고 해당 내용을 어떻게 수정하면 좋을지 고민해보시면 좋을 것 같다는 생각이 듭니다!💪

2024-03-10 16:47 UTC, dpcks0509 commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +            readPlayersName()
InputView, OutputView로 분리하였습니다!

2024-03-10 16:48 UTC, dpcks0509 commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        }
Controller에서 GameInformation 클래스로 책임 분리 하였습니다!

2024-03-10 16:49 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/card/Card.kt
> +            }
OutputView에서 처리하도록 변경하였습니다!

2024-03-10 16:50 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/card/Deck.kt
> +object Deck {
코드 전역에서 사용하기 위해 object로 선언하였는데 class로 선언하는게 더 맞는거 같아 class로 수정하였습니다!

2024-03-10 16:50 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/game/ScoreCalculation.kt
> +    }
에이스가 1점으로 시작해서 점수합계가 11점 이하일경우 보너스 점수 10점을 획득하도록 수정하였습니다!

2024-03-10 16:50 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/game/State.kt
> +        data object Hit : Running
유저가 뽑지 않았을때의 상태인 READY 상태를 추가하였습니다!

2024-03-10 16:51 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/player/Dealer.kt
> +        return ScoreCalculation.calculate(hand) <= 16
상수로 처리하였습니다!

2024-03-10 16:51 UTC, dpcks0509 commented on src/main/kotlin/blackjack/view/InputView.kt
> +}
view에서 처리하도록 분리하였습니다!

2024-03-10 16:52 UTC, dpcks0509 commented on src/test/kotlin/blackjack/CardTest.kt
> +}
테스트 코드 함수 네이밍 이해하기 쉽도록 수정하였습니다!

2024-03-10 16:52 UTC, dpcks0509 commented on src/test/kotlin/blackjack/DealerTest.kt
> +    }
Deck 객체 class로 변경하였습니다!

2024-03-10 16:52 UTC, dpcks0509 commented on src/test/kotlin/blackjack/DealerTest.kt
> +    }
@BeforeEach를 적용하여 test fixture를 적용해보았습니다!

2024-03-11 12:51 UTC, Gyuil-Hwnag requested changes
채드 안녕하세요!
해당 미션 전반적으로 구현을 새롭게 바꿔주셨네요~
기존 로직을 모두 바꾸는데 많이 힘드셨을텐데, 정말 고생 많으셨습니다👏

전체적으로 수정이 이루어져서 고민해보시면 좋을만한 내용들 코멘트가 많이 생겼는데 확인해주시면 감사하겠습니다.

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 
화이팅입니다💪

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +    }
해당 내용은 Delar의 뽑기와, Player의 뽑기로 함수를 만들어도 될 것 같다는 생각이 드는데, 채드의 생각은 어떠신가요??🤔

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/CardDeck.kt
> +    }
해당 내용은 자칫 잘못하면 에러를 유발할 수도 있다는 생각이 듭니다!

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/CardDeck.kt
> +class CardDeck {
CardDeck를 class 키워드로 설정하신 이유가 있을까요??
채드의 생각이 궁금합니다!

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/CardDeck.kt
> +    }
entries.flatMap 의 활용 좋네요~👍

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        participants.dealer.additionalDraw(cardDeck) { OutputView.outputDealerDraw(participants.dealer) }
해당 내용도 과연 Controller 에서 담당을 하고 있어야 하는 것인지에 대해서 고민을 해봐도 좋을 것 같습니다!💪

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/DrawDecision.kt
> +    }
해당 내용은 Input 에서 처리를 하도록 수정을 해보는 것은 어떠신가요??💪

이번 미션의 요구사항에는 아래와 같은 사항들이 존재를 하고 있습니다~
- 핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.
- UI 로직을 InputView, ResultView와 같은 클래스를 추가해 분리한다.

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        }.getOrThrow()
빈칸으로 들어오는 것등은 InputView 에서 처리하도록 수정해볼 수도 있겟다는 생각이 듭니다!!💪

이번 미션의 요구사항에는 아래와 같은 사항들이 존재를 하고 있습니다~
- 핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.
- UI 로직을 InputView, ResultView와 같은 클래스를 추가해 분리한다.

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/GameInformation.kt
> +    }
해당 조건들에 대해서는 하나의 함수로 묶을 수도 있겠다는 생각이 듭니다!💪

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/GameState.kt
> +}
해당 내용을 상태값으로 설정하면서 얻는 이점은 어떤 것이 있을까요??🤔
고민해보면 좋을 내용인 것 같아서 코멘트 남겨두었습니다~
채드의 생각을 자유롭게 남겨주세요!

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/Participant.kt
> +sealed class Participant(val name: ParticipantName, val gameInformation: GameInformation) {
sealed class를 잘 사용해주셨네요~👍
해당 내용을 sealed class로 작성하신 이유를 알 수 있을까요??
abstract, interface 등등 여러가지의 구현이 있을텐데, sealed class로 작성하신 이유가 궁금합니다!🤔

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/Participant.kt
> +    }
해당 메서드가 존재하는 이유가 궁금합니다!!🤔
해당 내용을 살펴보면 초기화시 Hit으로 지정해주는 것 외에 별 다른 동작을 한다고 생각이 들지 않아서 GameInformation.state의 초기 설정값을 Hit으로 지정하는 방법도 있지 않을까 싶어서 의견 남겨두었습니다~

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/Participant.kt
> +            if (gameInformation.score < 21) {
최대 점수의 경우도 하드코딩된 내용을 상수화를 해볼 수 있겠다는 생각이 듭니다!!💪

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/ParticipantName.kt
> +}
ParticipantName의 경우 Participant 에도 존재해도 될 것 같은데, 따로 분리한 이유가 궁금합니다!!🤔

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/Participants.kt
> +class Participants(val dealer: Dealer, val players: List<Player>) {
추가적으로 해당 객체를 만들게 된 이유에 대해서 궁금합니다~🤔

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/ScoreCalculator.kt
> +    }
요구사항에 맞게 조건을 수정해주셨네요~👍
수정이 필요한 것은 아니고, 참고하면 좋을 것 같아서 코멘트 남겨두었습니다!!
`만약 ACE에 대한 보너스 점수가 바뀌게 된다면 어떻게 좀더 유연하게 처리를 할 수 있을까요??`라는 고민도 해보면 좋을 것 같다는 생각이 듭니다🤔
1. CardNumber.BONUS_ACE로 ACE에 대한 점수를 관리해 볼수도 있겠네요~
2. ACE에 대한 점수 계산을 함수로 분리를 하는 방법도 있을 수 있겠다는 생각이 듭니다~

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/view/OutputView.kt
> +object OutputView {
아래의 요구사항을 고민해본다면 OutputView의 길이를 줄여볼 수 있겠다는 생각이 듭니다!!
각각 상황에 맞는 Output을 출력하도록 만든다면 다른 사람이 보더라도 가독성 측면에서 좋아질 수 있겠다는 생각이 듭니다!💪
- UI 로직을 InputView, ResultView와 같은 클래스를 추가해 분리한다.

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/view/OutputView.kt
> +    }
해당 내용은 Enum class 의 특징을 고민해보면 해당 코드는 사라질 수도 있겠다는 생각이 듭니다~💪

2024-03-11 12:51 UTC, Gyuil-Hwnag commented on src/test/kotlin/blackjack/CardDeckTest.kt
> +class CardDeckTest {
카드뭉치에서 카드를 모두 뽑는 경우 오류를 발생시킬 수 있는 로직이 있던데, 해당 내용도 테스트 해보는 것도 좋을 것 같다는 생각이 듭니다!💪

2024-03-11 13:42 UTC, dpcks0509 commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +    }
decidePlayerDecisions와 judgePlayerDraw 플레이어의 뽑기 함수를 하나로 통일하였고, judgeDealerDraw 딜러의 뽑기 함수를 새로 만들었습니다! 6324005963f3788857abfcc8d401d32d1757e5c9

2024-03-11 16:26 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/Participants.kt
> +class Participants(val dealer: Dealer, val players: List<Player>) {
List<Participant>를 파라미터로 받는 것으로 수정하고 딜러와 플레이어를 따로 get함수로 바깥에서 사용가능하게 수정하였습니다!

2024-03-11 16:42 UTC, dpcks0509 commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        }
Dealer에 있는게 더 맞다고 생각되어 Dealer로 함수 이동하였습니다!

2024-03-11 16:43 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/Participant.kt
> +    }
카드 받기 전 상태인 READY도 있으면 좋겠다고 생각하여 초기에는 READY상태에서 2장을 모두 딜링 받고 나면 HIT 상태로 변환하려 했는데 불필요한 코드라고 판단되어 초기상태를 HIT로 설정하고 해당 메서드는 삭제하였습니다!

2024-03-11 17:52 UTC, dpcks0509 commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        participants.dealer.additionalDraw(cardDeck) { OutputView.outputDealerDraw(participants.dealer) }
드로우 판단 로직을 각각 Player, Dealer로 이동하였습니다!

2024-03-12 02:54 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/CardDeck.kt
> +class CardDeck {
처음에는 CardDeck 한개로 게임 끝까지 사용하기 위해 object로 선언했는데 게임을 재시작할 경우를 생각하여 재사용하기 위해 class로 선언하였습니다! object로 선언하고 초기화하는 함수를 따로 만들어서 하는방법과 지금 방법 중 어떤방법이 더 좋은 방법인지 아직까지 고민입니다,,

2024-03-12 06:22 UTC, dpcks0509 commented on src/main/kotlin/blackjack/view/OutputView.kt
> +    }
해당 함수들을 enum class에 companion object에 함수로 선언하는 것으로 변경하였습니다!

2024-03-12 07:16 UTC, dpcks0509 commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        }.getOrThrow()
InputView에서 처리하도록 수정하였습니다!

2024-03-12 07:22 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/DrawDecision.kt
> +    }
InputView에서 처리하도록 수정하였습니다!

2024-03-12 07:39 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/GameInformation.kt
> +    }
하나의 함수로 수정하였습니다!

2024-03-12 07:40 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/ParticipantName.kt
> +}
원시값을 포장하라는 요구사항이 있어 따로 분리하였습니다!

2024-03-12 07:43 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/Participants.kt
> +class Participants(val dealer: Dealer, val players: List<Player>) {
Participants 객체를 생성하여 딜러와 플레이어들을 가져서 모든 참가자에 대한 정보를 담고 있으면 나중에 출력하거나 메소드에 값을 전달할때 중복코드를 줄일 수 있을것 같아 생성하게 되었습니다!

2024-03-12 07:54 UTC, dpcks0509 commented on src/main/kotlin/blackjack/view/OutputView.kt
> +object OutputView {
점수 출력과 결과 출력에 대한 부분을 ResultView로 분리하였습니다!

2024-03-12 09:00 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/GameState.kt
> +}
해당 내용을 상태값으로 설정해놓으면 Running과 FInished안에 다른 값들이 있어 세부적인 상태에 따라 계산을 다르게 할 수 있고,
게임이 진행중인 것을 State가 Running이냐 Finished냐 만을 가지고 게임 진행에 대한 판단을 더 쉽게 할 수 있을것이라고 생각하고 구현하였습니다!

2024-03-12 09:02 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/Participant.kt
> +sealed class Participant(val name: ParticipantName, val gameInformation: GameInformation) {
Participant라는 sealed class 안에서 Dealer와 Player를 묶어 동일한 느낌의 객체로 묶은 느낌을 주려고 했습니다.
abstract는 동일한 느낌의 객체로 묶는 느낌이 없어 제외 했고,
interface는 Dealer와 Player의 동일한 메서드를 Participant내에서 한번에 구현을 할 수 없어 제외하였습니다!

2024-03-12 09:16 UTC, dpcks0509 commented on src/test/kotlin/blackjack/CardDeckTest.kt
> +    }
테스트 코드명 수정하였습니다!

2024-03-12 09:16 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/ScoreCalculator.kt
> +    }
보너스 점수 계산 부분을 함수로 따로 분리하였습니다!

2024-03-12 15:43 UTC, Gyuil-Hwnag requested changes
채드 안녕하세요!

해당 코멘트 반영한 내용이 커밋이 푸쉬가 안된 것 같이 보이는데, 수정한 내용 반영한 후에 다시 리뷰 요청 부탁드리겠습니다!!
![스크린샷 2024-03-13 오전 12 42 40](https://github.com/woowacourse/kotlin-blackjack/assets/84956038/5a24e0a7-cd60-4a04-9e25-81e43240f34e)

이번 미션 남은 기간 화이팅입니다💪

2024-03-13 01:45 UTC, Gyuil-Hwnag requested changes
채드 안녕하세요!

해당 미션 구현 고생 많으셨습니다!
리뷰 반영하면서 구현한 내용 수정 너무 잘 해주셨습니다 💯

고민해보시면 좋을만한 내용들 코멘트를 달았으니 확인해주시면 감사하겠습니다.

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 
화이팅입니다💪

2024-03-13 01:45 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        }
혹시 해당 내용을 `try-catch`로 적용을 하신 이유가 있을까요??🤔

2024-03-13 01:45 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/CardNumber.kt
> +    }
해당 로직은 어떤 로직에 해당하게 될까요??🤔
아래의 요구사항이 있어서 한번 고민해보면 좋을 것 같다는 생각이 듭니다!!
- 핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.

2024-03-13 01:45 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/CardDeck.kt
> +        get() = _cards.toSet()
고민해보면 좋을 내용인 것 같아서 코멘트 남겨두었습니다~
아래의 두개의 구현은 어떤 차이점이 존재를 할까요??
~~~kotlin
    val cards: Set<Card>
        get() = _cards.toSet()
    
    val cards: Set<Card> = _cards.toSet()
~~~

2024-03-13 01:45 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/CardSymbol.kt
> +    }
해당 내용도 위의 CardNumber와 동일하게 어떤 로직에 해당하는지 고민을 해보면 좋을 것 같습니다!💪

2024-03-13 01:45 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/GameResult.kt
> +        get() = _dealerResult.toMap()
GameResult 객체로 딜러의 결과와 플레이어의 결과를 판별해주는 객체를 만드셨군요~

2024-03-13 01:45 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/Participant.kt
> +sealed class Participant(val name: ParticipantName, val gameInformation: GameInformation) {
타당한 이유 정말 좋은 것 같습니다~👍
확실히 구현하신 내용을 살펴보면 interface로 만들기에는 애매하다는 생각이 들 수도 있겠군요!

2024-03-13 01:45 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/GameInformation.kt
> +        get() = _score
블랙잭의 구현에는 아래와 같은 요구사항도 있습니다!!
해당 요구사항을 고려한다면, 어떻게 수정을 할 수 있을까요??💪
- 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

2024-03-13 01:45 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        return Participants(participants)
해당 내용은 과연 Controller에서 책임을 가지고 해야 하는 내용이 맞을지 고민해봐도 좋을 것 같습니다!!
해당 내용을 적용하다 보면 Participants 객체에 있는 `getDealer()` `getPlayers()` 에서 리스트를 잘라서 반환하는 내용이 정리가 될 수도 있다는 생각이 듭니다!!💪

2024-03-13 01:45 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/Participants.kt
> +    }
Controller 에서 남겨두었던 코멘트를 살펴보면 해당 함수들에서 리스트를 변환하는 내용도 정리가 될 수 있을 것 같다는 생각이 듭니다~💪

2024-03-13 01:45 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/Result.kt
> +    }
이전에 남겨두었던 대로 해당 내용은 어떤 로직에 들어가야 하는 로직일까요??
이전에 InputView 에서 Extenions로 처리하던 내용은 아래와 같이 수정을 해보도록 요구한 내용이었습니다~

<details>
<summary>힌트</summary>

```
// Result Enum 객체
enum class Result(val label: String) {
    DEALER_WIN("승"),
    PLAYER_WIN("무"),
    TIE("패")
}

// 사용
gameResult.playerResults.withIndex().map { (index, playerResult) ->
    println(
        ResultView.MESSAGE_PLAYER_RESULT.format(
            gameResult.participants.getPlayers()[index].name,
            playerResult.label,
        ),
    )
}
```

</details>

2024-03-13 01:45 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/ScoreCalculator.kt
> +object ScoreCalculator {
ScoreCalculator를 obejct 키워드를 사용하여 잘 구현 해주셨네요~👍

2024-03-13 01:45 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/view/InputView.kt
> +        }
해당 내용에서도 `try-catch`로 작성을 하신 이유가 있을까요??
이전 로또 미션에서 `try-catch`를 사용하지 않도록 요구사항이 있어서 그때의 기억을 되짚어봐도 좋을 것 같다는 생각이 듭니다!!💪

2024-03-13 01:45 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/view/ResultView.kt
> +        }
Format 까지 너무 깔끔하게 잘 사용을 해주셨네요~💯

2024-03-13 01:45 UTC, Gyuil-Hwnag commented on src/test/kotlin/blackjack/CardDeckTest.kt
> +    }
리뷰 반영 잘해주셨네요~💯

2024-03-13 01:45 UTC, Gyuil-Hwnag commented on src/test/kotlin/blackjack/DealerTest.kt
> +    }
테스트 코드에 대한 함수명 너무나 잘 작성해주셨습니다~
고민해보면 좋을 내용인 것 같아서 코멘트 남겨두었습니다!!
테스트 함수명을 `행위 -> 결과`를 한번에 알 수 있도록 수정을 해보는 것도 도움이 될 것 같다는 생각이 듭니다!!
현재는 테스트 함수의 내용이 많지 않지만, 추후 내용이 많아지게 되면, 현재의 함수명만을 보고 `그래서 어떤 결과를 알 수 있는건데??`라는 의문이 생기지 않을까 싶기는 합니다!!

2024-03-13 02:21 UTC, dpcks0509 commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        }
카드를 52장을 다 뽑았을때 카드를 한장 더 뽑으려고 하면 예외를 발생하는데, 이럴때 저는 현재까지의 게임 결과를 출력하기 보다는 게임이 정상적으로 진행이 되지않았다고 판단하여 무효처리하고 게임결과를 출력하지 않고 바로 게임이 종료되는 것을 의도하였습니다.
코드를 다시보니 run()함수 내에서 try catch를 하는것이 더 적절하다고 판단되어 위치를 이동하였습니다!

2024-03-13 02:28 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/CardSymbol.kt
> +    }
enum class에서 label을 만들어 문자열을 처리하도록 수정하였습니다!

2024-03-13 02:28 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/Result.kt
> +    }
enum class에서 label을 만들어 문자열을 처리하도록 수정하였습니다!

2024-03-13 02:33 UTC, dpcks0509 commented on src/test/kotlin/blackjack/DealerTest.kt
> +    }
함수명에서 행위, 결과를 한번에 알아 볼 수 있도록 수정하였습니다!

2024-03-13 04:10 UTC, dpcks0509 commented on src/main/kotlin/blackjack/view/InputView.kt
> +        }
두번째로 리뷰요청을 보낼때 try-catch문을 사용하지않고 runCatching을 이용해서 하는 방법으로 구현 했었는데, 이전 리뷰에서 입력에 대한 피드백이 있어서 try-catch로 수정했던것 같습니다.(지금은 리뷰가 안보이네요🥲)
try-catch 사용 관련해서는 수업시간에 다른 크루가 물어봤었는데 쓰지 말라고 한게 아니라고 하셔서 사용하였습니다!

2024-03-13 04:12 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/CardNumber.kt
> +    }
enum class에서 label을 만들어 문자열을 처리하도록 수정하였습니다!

2024-03-13 04:20 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/CardDeck.kt
> +        get() = _cards.toSet()
첫번째 방법은 _cards의 값이 변할때마다 같이 cards의 값을 업데이트 해주지만,
두번째 방법은 처음 한번만 값을 초기화해주고 이후에 _cards의 값이 변홰도 cards의 값이 업데이트 되지 않습니다!

2024-03-13 05:12 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/Participants.kt
> +    }
Participants 객체가 아무 기능을 가지지 않아 필요없을것 같다고 판단되어 삭제하였습니다!

2024-03-13 05:13 UTC, dpcks0509 commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        return Participants(participants)
Participants 객체가 아무 기능을 가지지 않아 필요없을것 같다고 판단되어 삭제하였습니다!

2024-03-13 05:24 UTC, dpcks0509 commented on src/main/kotlin/blackjack/model/GameInformation.kt
> +        get() = _score
ScoreCalculator를 사용하면 score 변수가 따로 필요하지 않아서 score를 삭제하여 인스턴스 변수를 2개로 낮추었습니다!

2024-03-14 03:39 UTC, Gyuil-Hwnag approved these changes
채드 안녕하세요~ 
해당 미션 너무 고생 많으셨습니다! 
리뷰 반영 정말 잘 해주셨네요💯

해당 미션은 다음 미션 진행을 위하여 머지하도록 하겠습니다.
리뷰 반영을 해나가면서 객체에 대한 책임을 가지는 영역과 그에 따른 분리가 잘 적용이 되어가는게 정말 인상적이었습니다!!👍

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏
다음 미션도 화이팅입니다💪

2024-03-14 03:39 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/CardNumber.kt
> +}
CardNumber에 대해서 enum을 정말 잘 사용해주셨네요~👍

2024-03-14 03:39 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/model/GameResult.kt
> +class GameResult(val dealer: Dealer, val players: List<Player>) {
Delear, Players를 생성자로 받도록 수정해주셨군요~👍

2024-03-14 03:39 UTC, Gyuil-Hwnag commented on src/main/kotlin/blackjack/view/InputView.kt
> +        }
타당한 이유가 있다면 좋습니다~👍

2024-03-14 03:40 UTC, merged