[블랙잭] 예니 2단계 미션 제출합니다.
woowacourse/kotlin-blackjack pull request #83
Opened 2024-03-13 13:54 UTC by JoYehyun99

잛 부탁드립니다 ☺️

2024-03-14 09:08 UTC, vagabond95 commented on src/main/kotlin/blackjack/controller/BlackjackController.kt
> +                Player(playerName, createInitialHand(deck), BetAmount(InputView.readBetAmount(playerName)))
```suggestion
                Player(playerName, createInitialHand(deck), BetAmount(amount))
```
호출은 최대한 중첩하지 않도록 신경써보면 좋을 것 같아요.
중첩이 두번이상 생길 수록 가독성이 급격하게 떨어질 것 같습니다.

2024-03-14 09:09 UTC, vagabond95 commented on src/main/kotlin/blackjack/model/BetAmount.kt
> +    operator fun unaryMinus(): Double = -amount
베팅금액을 차감했을때, 음수가 되는 경우에 대한 처리가 있으면 좋을 것 같아요!

2024-03-14 09:10 UTC, vagabond95 commented on src/main/kotlin/blackjack/model/Participants.kt
> +    fun getDealerProfits(playersResult: Map<Player, Double>): Double = playersResult.entries.sumOf { it.value } * (-1)
```suggestion
    fun getDealerProfits(playersResult: Map<Player, Double>): Double = playersResult.entries.sumOf { it.value } * (-1)
```
result 보다는 기존에 적어주신 profit 이라고 네이밍이 지어져야 명확할 것 같습니다!

2024-03-14 09:11 UTC, vagabond95 commented on src/main/kotlin/blackjack/model/Participants.kt
> +    fun getDealerProfits(playersResult: Map<Player, Double>): Double = playersResult.entries.sumOf { it.value } * (-1)
players 의 수익을 외부에서 전달 받는 것이 아니라, 내부에서 바로 참조할 수 있지 않을까요?

2024-03-14 10:03 UTC, JoYehyun99 commented on src/main/kotlin/blackjack/controller/BlackjackController.kt
> +                Player(playerName, createInitialHand(deck), BetAmount(InputView.readBetAmount(playerName)))
넵! 해당 부분 분리하겠습니다~

2024-03-14 10:35 UTC, JoYehyun99 commented on src/main/kotlin/blackjack/model/Participants.kt
> +    fun getDealerProfits(playersResult: Map<Player, Double>): Double = playersResult.entries.sumOf { it.value } * (-1)
플레이어와 딜러의 수익을 합쳐서 반환하도록 수정했습니다~

2024-03-15 09:49 UTC, vagabond95 requested changes
미션의 마무리까지 얼마 남지 않은게 느껴지네요 ㅎㅎ

추가로 남긴 코멘트 검토 후, 리뷰 요청 부탁드릴게요~!

2024-03-15 09:49 UTC, vagabond95 commented on src/main/kotlin/blackjack/model/Participants.kt
> +            player.calculateProfit(winningResult)
해당 단계는 player 에서 한번의 요청으로 구할 수 있지 않을까요?
같은 결과를 가져올 수 있다면, 세부 구현을 드러내지 않았을 때 얻을 수 있는 이점은 무엇일까요?

2024-03-15 09:49 UTC, vagabond95 commented on src/main/kotlin/blackjack/model/Participants.kt
> +    private fun getDealerProfits(playersProfits: Map<Player, Double>): Double = playersProfits.entries.sumOf { it.value } * (-1)
playersProfits 이라고 네이밍만 제한했을 뿐, 타입은 동일하기에 dealer 의 profit 을 넣더라도 이를 감지하거나 제한할 수가 없는 상황인데요. 좀 더 개선해볼 수 있을 것 같습니다 :)

2024-03-17 07:26 UTC, JoYehyun99 commented on src/main/kotlin/blackjack/model/Participants.kt
> +            player.calculateProfit(winningResult)
player가 자신의 수익률을 계산하는 로직을 캡슐화하게 되면
Participants에서 player의 `getWinningResult`와 `calculateProfit`의 호출 순서를 몰라도 되고,
때문에 player의 책임이 더욱 명확하게 분리될 것 같습니다...!

2024-03-17 08:25 UTC, JoYehyun99 commented on src/main/kotlin/blackjack/model/Participants.kt
> +    private fun getDealerProfits(playersProfits: Map<Player, Double>): Double = playersProfits.entries.sumOf { it.value } * (-1)
제가 피드백의 의도를 잘 파악한건지는 모르겠지만,,! 
일단 딜러의 수익 계산 로직을 따로 분리하지 않고 `getParticipantsProfits` 에서 한 번에 계산할 수 있도록 수정했습니다!

2024-03-17 15:09 UTC, vagabond95 approved these changes
1단계에서 구조적으로 완성도가 높아서 2단계는 크게 코멘트 드릴 부분이 보이지 않았어요 ㅎㅎ
블랙잭 미션에서 갑자기 난이도가 확 뛰셨을텐데, 마무리하시느라 정말 고생 많으셨습니다. 💯 

해당 미션은 여기서 마무리할게요. 남은 미션까지 화이팅이십니다~!

2024-03-17 15:09 UTC, merged