[로피] 1단계 블랙잭 제출합니다.
woowacourse/kotlin-blackjack pull request #9
Opened 2023-03-02 09:00 UTC by Choisehyeon

안녕하세요 리뷰어님! 페어와 열심히 블랙잭 미션을 했습니다. 리뷰 잘 부탁드립니다!!

2023-03-03 12:18 UTC, BeokBeok requested changes
블랙잭 미션하시느라 고생하셨습니다. 👍 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2023-03-03 12:18 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/BlackJackBuilder.kt
> +        participants.all().map {
```suggestion
        participants.all().forEach {
```
무언가를 변환하는 것이 아니라면 forEach를 활용해보면 어떨까요?

2023-03-03 12:18 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/BlackJackGame.kt
> +    }
BlackJack 클래스와 관련된 확장 함수를 작성해주셨네요. 👍 
BlackJack 클래스 내의 멤버 함수로 구현하는 것과, 다른 클래스에서 BlackJack의 확장함수를 만드는 것은 각각 어떤 장점이 있을까요?
만약 다른 개발자가 guestsTurn 함수와 dealerTurn 함수가 BlackJackGame에 정의가 되어있을 것이라 예상할 수 있을까요?

2023-03-03 12:18 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/CardDeck.kt
> +    fun shuffle() = cards.shuffle()
외부에서 shuffle 함수를 호출해줘야할까요?
CardDeck 객체를 생성할 때 shuffle 해서 전달해줘도 되지 않을까요?

2023-03-03 12:18 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/Cards.kt
> +            }.flatten()
아래 프로그래밍 요구사항을 적용해보면 어떨까요?
- indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.

2023-03-03 12:18 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/Cards.kt
> +    fun toList() = cards.toList()
toList라는 함수를 외부에서 호출해줘야할까요?
외부에서 cards 변수에 접근해서 값을 조회하도록 개선해보면 어떨까요?

2023-03-03 12:18 UTC, BeokBeok commented on src/main/kotlin/blackjack/view/OutputView.kt
> +        }
지금과 같은 구조에서는 enum이 변경될 때마다 이 코드들도 변경을 해줘야합니다.
enum만 변경해도 이 코드들이 영향을 미치지 않도록 코드를 개선해보면 어떨까요?

2023-03-03 12:18 UTC, BeokBeok commented on src/test/kotlin/blackjack/domain/NameTest.kt
> +    fun `이름은 1~20자 이외면 에러난다`(name: String) {
20자가 넘을 경우에 예외처리가 발생하는 것으로 이해하고 있습니다.
테스트 코드에서는 가급적이면 경계값을 위주로 테스트를 하는 것이 좋습니다.
여기에서는 이름을 21자에 대해서 테스트를 하는 것으로 개선하는 것을 권장합니다.

2023-03-06 05:19 UTC, Choisehyeon commented on src/main/kotlin/blackjack/domain/Cards.kt
> +    fun toList() = cards.toList()
캡슐화를 위해 toList 함수를 사용해서 호출해줬는데 직접 접근하게 된다면 Card.card.toList()과 같이 될 것 같아서 캡슐화를 하기 위해 위 방식으로 진행했습니다!

2023-03-06 05:27 UTC, Choisehyeon commented on src/main/kotlin/blackjack/view/OutputView.kt
> +        }
저는 이부분이 출력에 관한 부분이라고 생각해서 enum에서 값을 넣어주는 것이 뷰의 역할을 가지고 있다는 생각이 들어서 위와 같이 진행했습니다!

2023-03-06 14:06 UTC, BeokBeok requested changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2023-03-06 14:06 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/result/Outcome.kt
> +        fun User.winTo(other: User): Outcome =
winTo라는 확장함수를 잘 구현해주셨네요. 👍 
확장함수는 마치 클래스 멤버 함수인 것처럼 사용할 수 있는 강력한 장점이 있으나, 외부에서 정의가 가능하기 때문에 중복으로 확장함수를 만들기 쉬우며, 멤버 함수가 아닌 정적 함수로 만들어지기 때문에 프로그램이 종료될 때까지 메모리에서 해제되지 않는 단점이 있습니다.
winTo 함수를 확장함수 또는 멤버함수로 구현했을 때 각각 어떤 장단점이 있을지 고민해보면 어떨까요?

2023-03-06 14:06 UTC, BeokBeok commented on src/main/kotlin/blackjack/view/OutputView.kt
> +        }
만약 CardValue의 값이 추가가 된다면, 별도로 신경을 쓰지 않는 이상 else 문으로 동작하게 되면서 예상치 못한 오류가 발생할 수 있습니다.
when을 exhaustive하게 작성해보면 어떨까요?

ref. https://kotlinlang.org/docs/whatsnew16.html#stable-exhaustive-when-statements-for-enum-sealed-and-boolean-subjects

2023-03-06 14:06 UTC, BeokBeok commented on src/test/kotlin/blackjack/domain/blackjack/BlackJackBuilderTest.kt
> +    fun `세팅이 된다`() {
"세팅이 된다" 라는 것은 어떤 것을 의미할까요?
다른 개발자가 보았을 때에도 어떤 것을 의미하는지 알 수 있도록 함수명을 작성해보면 어떨까요?

2023-03-08 05:26 UTC, Choisehyeon commented on src/main/kotlin/blackjack/domain/result/Outcome.kt
> +        fun User.winTo(other: User): Outcome =
확장함수 장점 - 확장함수를 사용하면 코드가 간결해져서 가독성이 높다. 기존 클래스를 수정하지 않고도 새로운 기능 추가 할 수 있다.
확장함수 단점 - 네임스페이스 오염이 발생할 수 있다. 확장 함수는 클래스 외부에서 정의되므로, 클래스 내부의 함수와 이름이 충돌할 수 있다. 클래스의 캡슐화가 위반될 수 있다.
멤버함수 장점 - 클래스의 캡슐화를 보호할 수 있다.  클래스 내부에서 수행되므로 코드를 읽는 사람이 이를 의도적으로 이해하기 쉽다.
멤버함수 단점 - 멤버 함수를 사용하면 클래스의 구조와 밀접하게 연관된 작업만 수행할 수 있기 때문에, 클래스의 구조를 변경하지 않고 새로운 기능을 추가하기 어려울 수 있다.

2023-03-08 12:56 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪 
다음 미션을 진행하시면서, 추가로 작성된 코맨트들도 반영해주세요. 🙏

2023-03-08 12:56 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/blackjack/BlackJackBuilder.kt
> +    }
```suggestion
    fun initDraw() {
        participants.all().forEach {
            it.draw(cardDeck.nextCard())
            it.draw(cardDeck.nextCard())
        }
    }
```
`=` 을 사용하게 되면, 흔히 코드만 봤을 때 마치 리턴값이 있는 것처럼 보여요.
리턴타입이 없는 경우에는 `=` 보다는 중괄호를 사용해보면 어떨까요? (이하 관련 내용 동일)

2023-03-08 12:56 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/blackjack/BlackJackGame.kt
> +        }
binary condition인 경우에는 when 보다는 if문 사용을 권장해요.

ref. https://kotlinlang.org/docs/coding-conventions.html#if-versus-when

2023-03-08 12:56 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/card/CardValue.kt
> +    }
테스트 코드를 작성해보면 어떨까요?

2023-03-08 12:56 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/blackjack/BlackJackBuilder.kt
> +}
Builder 패턴은 호출 순서와 상관 없이, build 함수를 호출하는 순간 객체가 정상적으로 만들어져야 합니다.
하지만, 아래와 같은 코드를 작성하게 되면 어떻게 될까요?
```kotlin
val blackjack = BlackJackBuilder().build()
blackjack.participants
```
이를 해결하기 위해서는 어떻게 하면 좋을지 고민해보면 어떨까요? (이하 관련 내용 동일)
Builder 패턴의 장단점 및 지연초기화의 장단점에 대해서 학습해보면 좋을 것 같아요.

2023-03-08 12:56 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/result/Outcome.kt
> +        fun gameResult(user: User, other: User): Outcome =
함수명만 봤을 때에는 "게임 결과"라는 의미로 해석돼요.
하지만 리턴타입은 Outcome이네요.
함수명만 봤을 때 리턴타입이 Outcome임을 알 수 있도록 개선해보면 어떨까요?

2023-03-08 12:56 UTC, BeokBeok commented on src/main/kotlin/blackjack/view/OutputView.kt
> +            -> this.value.toString()
```suggestion
            CardValue.TEN -> this.value.toString()
```
사소하지만, `->` 는 같은 라인에 작성하는 것을 권장합니다.

2023-03-08 12:56 UTC, merged