[블랙잭] 누누 2단계 미션 제출합니다.
woowacourse/kotlin-blackjack pull request #92
Opened 2024-03-14 16:21 UTC by jinuemong

리뷰어님 안녕하세요 누누입니다.

주요 변경사항을 적어보았습니다.
- 1단계에서의 수정사항을 적용하였습니다.
- Wallet 모델 추가 
- participant의 생성자 name:String -> wallet: Wallet으로 변경
- dealer의 정산 기능 적용 
- 베팅 결과 정산

이전 step의
https://github.com/woowacourse/kotlin-blackjack/pull/63#discussion_r1523224418
커맨트에 대한 답변을 달았는데 의도를 이해하고 적용하였으나, 이해가 안가는 부분이 있어서 comment를 달았습니다. 확인해주시면 감사하겠습니다!
🙇‍♂️

2024-03-15 04:10 UTC, laco-dev requested changes
2단계 미션 고생 많으셨습니다.

점진적으로 개선 해 보면 좋을 듯 합니다.
질문주신 내용 포함해서 의견 남겨드렸습니다. 🙏🏻

2024-03-15 04:10 UTC, laco-dev commented on src/main/kotlin/blackjack/model/HandCard.kt
> +        }
`private set` 을 사용하는 올바른 사례가 아닙니다.
https://kotlinlang.org/docs/properties.html

backing property랑 비교했을 때 어떤 차이인지 고민해보시면 좋겠습니다.

2024-03-15 04:10 UTC, laco-dev commented on src/main/kotlin/blackjack/model/Wallet.kt
> +data class Wallet(val name: String) {
참가자가 이름을 가지지 않고, 지갑에 이름을 붙이는게 맞나요?
인스턴스 변수 3개 조건을 억지로 지키려고 만들어진 것 같은 느낌이 듭니다.
우선은 3개를 사용하더라도, 더 좋은 구조라고 생각이 든다면 그렇게 해주시면 됩니다.

> 딜러는 "딜러"라는 이름을 가진다.
> 딜러는 "딜러"라는 이름의 지갑을 가진다.

2024-03-15 04:10 UTC, laco-dev commented on src/main/kotlin/blackjack/model/Wallet.kt
> +    }
현재 요구사항에서는 돈이 동적으로 변경될 일이 없는 것 같은데요.
상태를 동적으로 변경할 수 있도록 만든 이점이 있을까요?

2024-03-15 04:10 UTC, laco-dev commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +    }
순차적으로 실행하는 내용 관련해서 의견을 하나 더 드리자면,

원래 함수란, 무언가를 반환하도록 설계되었습니다.
만약 아무것도 반환하지 않는다면 사이드 이펙트를 발생시킨다는 것을 의미할 수 있으니까요.

지금 구조에서는 컨트롤러가 클래스 필드로 게임매니저를 가지고 있기 때문에 어디서든 접근할 수 있습니다.
그렇기 때문에 함수를 여러개로 나누어서 그때그때 접근하는게 편할지도 모릅니다.

하지만 지금까지 얘기한 것과 같이 문제가 생길 수도 있는것도 사실입니다.
아래 코드랑 비교했을때 어떤 차이가 있는지 고민 해보시면 좋겠습니다.

```kotlin
fun runBlackJackGame() {
  val gameManager = createGameManager()
  readyGame(gameManager)
  ...
  val gameResult: GameResult = playGame(gameManager)
  showResult(gameResult)
}
```

2024-03-15 05:52 UTC, jinuemong commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +    }
아하 참고해주신 코드로 보니까 어느정도 이해가 됩니다.
꼼꼼한 답변 감사드립니다.
사이드 이펙트에 대해서 좀 더 공부를 해보고, 코드를 짤 때 고민해봐야겠습니다.  🙇‍♂️

2024-03-15 05:54 UTC, jinuemong commented on src/main/kotlin/blackjack/model/Wallet.kt
> +    }
베팅 금액을 잃었다면 동적으로 변경하는 것 아닌가요?
result로 출력만 한다면 베팅한 금액에 대한 결과만 가지고 있는 것이지,
실제로 플레이어의 베팅 금액에 영향을 주지 않는다고 생각했습니다.
동적으로 변경하여 베팅 금액에 대한 계산 후 변경을 진행하였습니다.

2024-03-15 08:05 UTC, jinuemong commented on src/main/kotlin/blackjack/Application.kt
> +    blackJackController.runBlackJackGame()
와 예시로 보니까 이해가 너무 잘되네요.
제가 의문을 가졌던 부분이 한번에 해결된 것 같아서 좋습니다.
그렇다면 지금 코드가 짜여진 상황에서 컨트롤러에 runBlackJackGame 함수를 생성,
해당 함수에서 각  플로우를 진행한다면  적절한 책임 분류라고 할 수 있을까요?
메인에서는 한 번의 동작으로 진행되긴 합니다.

2024-03-15 08:11 UTC, jinuemong commented on src/main/kotlin/blackjack/model/Wallet.kt
> +data class Wallet(val name: String) {
저는 wallet에 신분증과 베팅 머니를 저장하는 그림을 생각했습니다.
다시보니 네이밍에 문제가 있었던 것 같습니다.
UserInformation으로 전환하니 구조가 괜찮아 진 것 같습니다.

2024-03-15 14:44 UTC, laco-dev commented on src/main/kotlin/blackjack/Application.kt
> +    blackJackController.runBlackJackGame()
정답을 알고 계신 듯 합니다. 어떤 답변을 드려야 좋을지 모르겠네요.
적어도 관심사가 컨트롤러와 메인 클래스가 명확하게 분리된 것은 사실이겠네요

2024-03-15 15:26 UTC, laco-dev requested changes
피드백 고생 하셨습니다.

여러가지 고민을 하신 흔적이 보이네요.
하지만 다시 2단계 기능 구현으로 돌아가보면 핵심적인 부분에 대한 고민이 다시 필요할 것 같아요. 🙇🏻

2024-03-15 15:26 UTC, laco-dev commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        val bettingResults = gameManager.getDealer().settleBettingMoneys(gameResult)
1. 딜러가 게임결과를 의존해서 수익률을 계산하는 것
2. 게임 결과를 통해 수익률을 판단하는 것

같은 기능에 대해 어떻게 의존성을 가지도록 하는게 적절하다고 생각하시나요?
코드가 복잡하게 만들어졌기 때문에 책임과 구현 위치가 적절한지 묻는 질문입니다.

2024-03-15 15:26 UTC, laco-dev commented on src/main/kotlin/blackjack/model/CardDeck.kt
> +            cards.offer(card)
ShuffleCardDeck과 generateCardDeck()은 어떤 차이가 있는건가요?
둘다 셔플하는거 아닌가요?

2024-03-15 15:26 UTC, laco-dev commented on src/main/kotlin/blackjack/model/Dealer.kt
> +class Dealer(userInformation: UserInformation = UserInformation(DEFAULT_DEALER_NAME)) : Participant(userInformation) {
유저정보가 되서 더 좋아졌다고 생각하셨지만...
사실 Information이라는 이름은 객체지향 설계에 굉장한 피곤함을 주는 이름입니다.

왜냐하면 만능이거든요.
정보에는 모든게 다 들어갈 수 있고, 모든 게 다 있으니 아무런 코드를 넣어도 되니까요.

2024-03-15 15:26 UTC, laco-dev commented on src/main/kotlin/blackjack/model/GameResult.kt
> +    }
같은 함수이름인데 서로 다른 구현처럼 보이네요! 맞나요?

2024-03-15 15:26 UTC, laco-dev commented on src/main/kotlin/blackjack/model/BlackJack.kt
> +        if (handCard.checkStateWithCardCount()) {
21점일 때 이 함수로 빠지는데, 카드가 2장이 아니면 어떤 상태가 되는건가요?

2024-03-15 15:26 UTC, laco-dev commented on src/main/kotlin/blackjack/model/Proceeds.kt
> +)
이 객체는 무슨 역할을 하는지 알려주세요. 🙇🏻 
객체 이름과 상태를 봐도 모르겠어서 질문 드립니다.

2024-03-15 15:26 UTC, laco-dev commented on src/main/kotlin/blackjack/model/Dealer.kt
> +    }
2단계의 핵심 기능입니다. 왜 단위 테스트를 작성하지 않았을까요?
아마 아래 테스트를 짜야 한다면, 머리가 아파지실 거라고 생각이 듭니다. 😱 

> 블랙잭 상태라면 수익률은 1.5배이다
> 스테이 상태는 수익률이 1배이다.
> 버스트 상태는 수익률이 0배이다.
> 히트 상태는 수익률 ?????

> 블랙잭으로 승리하였다면 1.5배의 수익금을 획득한다.
> 스테이로 승리하였다면 1배의 수익금을 획득한다.
> 버스트라면, 수익금은 0이다.
> .....

2024-03-15 15:26 UTC, laco-dev commented on src/main/kotlin/blackjack/view/OutputView.kt
> +        player.openInitCards().let { playerInitCards ->
let과 같은 범위 지정 함수는, 코드를 편하게 작성할 수 있지만 적절하게 사용하지 않으면 오히려 가독성을 해칠수도 있습니다.

범위 지정 함수의 여러 레퍼런스를 찾아 보시고, 프로그래밍 요구사항의 indent를 늘리지 않도록 하는 것을 지켜보도록 해보세요

2024-03-16 02:15 UTC, jinuemong commented on src/main/kotlin/blackjack/model/Proceeds.kt
> +)
한 게임에 대한 수익을 가지고 있습니다.
이름에 대한 뜻이 너무 많아서 **revenue** 로 전환하였습니다.

2024-03-16 02:20 UTC, jinuemong commented on src/main/kotlin/blackjack/model/BlackJack.kt
> +        if (handCard.checkStateWithCardCount()) {
Stay 상태가 되는게 맞나요? 
저는 21점인지 판단은 유저가 해서 Hit 상태를 유지하는게 맞다고 봤습니다.
이는 너무 현실세계에 몰입한 것일까요?
자동으로 Stay 상태가 되는 것이 아닌 유저가 본인의 점수 계산을 실수할 수 도 있다고 생각했습니다.
어쩌면 블랙잭 규칙을 제대로 모르는 것일 수도 있겠군요.. 수정하였습니다.

2024-03-16 03:18 UTC, jinuemong commented on src/main/kotlin/blackjack/model/GameResult.kt
> +    }
구현도 이름도 다르지 않나요? 질문의 의도를 모르겠습니다

2024-03-16 03:42 UTC, jinuemong commented on src/main/kotlin/blackjack/model/GameResult.kt
> +    }
의존성을 줄이다보니 getPlayerResult 함수가 없어져서 고민 사항이 해결되었습니다.

2024-03-16 04:59 UTC, jinuemong commented
[2단계 3차 리팩토링] 안녕하세요 리뷰어님 꼼꼼한 답변 감사드립니다.🙇‍♂️
테스트 코드를 작성하면서 핵심 로직에 오류가 있음을 발견하고 수정하였습니다.
단위 테스트를 진행하지 않은 이유는.. 까먹었습니다.. 저는 TDD가 아직 익숙하지 않군요😭
단위 테스트를 통해서 로직 오류를 발견하고, 로직 수정과 실제 기능 테스트를 진행하였습니다.
단순 수정 사항은 🚀을 달았고 궁금한 점은 코맨트 남겼습니다 !

2024-03-16 06:19 UTC, laco-dev requested changes
피드백 잘 반영 해주셨습니다.

점점 나아지는 모습이 좋았습니다.
코드 양이 많아지다보니 나누는 과정에서 역할을 정하는데 어려움이 있었을 것 같은데요.

코드 관점에서 어떻게 개선하면 좋을지 힌트를 조금 남겨두었습니다.
모든 내용을 반영할 필요는 없고, 어떤 의도로 피드백을 드렸는지 이해 해주시면 좋겠습니다.

2024-03-16 06:19 UTC, laco-dev commented on src/main/kotlin/blackjack/model/GameResult.kt
> +    }
`getPlayerResult()` 함수는 반환 타입으로 하여금, 승부 결과를 예측할 수 있는데
딜러는 파라미터에 해당하는 반환 타입이 무엇인지 함수 이름으로 충분히 전달 되고 있는지를 의도했습니다.

2024-03-16 06:19 UTC, laco-dev commented on src/main/kotlin/blackjack/model/GameResult.kt
> +            Result.DRAW -> 0f
무승부도 자기 배팅 금액을 그대로 돌려받지 않나요?

2024-03-16 06:19 UTC, laco-dev commented on src/main/kotlin/blackjack/model/Participant.kt
> +        require(wallet.identification.name.length <= MAX_NAME_LENGTH) {
이건 참가자의 규칙이 맞나요? 아니면 Identifier의 규칙이 맞나요?

2024-03-16 06:19 UTC, laco-dev commented on src/test/kotlin/blackjack/model/BettingPayoutTest.kt
> +        val gameResult = gameManager.calculateGameResult()
이 테스트는 GameManager를 테스트 하고 싶은 걸까요? 
아니면 GameResult를 테스트 하고 싶은 걸까요?

GameResult에서도 동일한 테스트가 있다면, 불필요한 중복 테스트가 되지는 않을까요?

2024-03-16 09:38 UTC, jinuemong commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +            }
이 말이 잘 이해가 가지 않군요 
forEach를 사용한 것은 잘못 사용한 것을 인지하였습니다.
하지만 딜러와 플레이어가 같은 참가자로써 각자 1개의 카드, 2개의 카드만 공개하는 것이 일관성이 맞지 않는다는 것이 이해가 되지 않습니다.
요구사항을 만족하기 위해서 로직을 분리하는 것이 아닌 각 카드들을 무조건 2장씩 공개하고 출력할 때만 한 장만 출력하라는 말씀이신가요?
그럼 딜러와 플레이어로 굳이 나누는 이유는 뭐가 있을까요?
저는 이 기능을 일관성있게 유지하기 위해서 플레이어와 딜러의 로직을 하나로 합친다면 굳이 나눌 필요가 있는지 생각이 듭니다.
그냥 참가자로 모두 생성하고 딜러라는 이름을 가진 참가자만 딜러로 구분하면 되는 것이 아닐까요?
로직을 분리하기 위해서 플레이어와 딜러로 나눴는데 로직을 합치라는 이유가 궁금합니다.
플레이어의 오류에 대한 출력문은 수정하였습니다.

2024-03-16 09:49 UTC, jinuemong commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +            }
말씀하신 예시처럼 participants로 변경하여 딜러의 내용을 출력하면 리뷰어님이 전에 말씀하신 딜러가 첫 번째 참가자라는 것을 보장하지 않는 것이 됩니다.
이전에 딜러가 첫번째 참가자라는 것을 보장한 코드를 보고 participants의 생성자를 dealer와 players로 바꾸라고 하셨습니다. 
이렇게 되면 결국에 원래 코드로 돌아가는 것을 원하시는지 궁금합니다.
오히려 일관성을 유지하기 위해서 participants로 전환하고, 이로 인해서 출력 시 딜러가 첫 번째 출력으로 나오지 않는다면 이것은 뷰의 일관성을 해치는 것은 아닐까요?.. 코드를 고치면서 생각이 많아집니다..

2024-03-16 09:51 UTC, jinuemong commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +    private fun playGame(gameManager: GameManager) {
이런 방법이 있었군요, 
확실히 코드와 함께 설명해주시니 이해가 잘 됩니다.
정말 감사합니다🙇‍♂️

2024-03-16 09:59 UTC, jinuemong commented on src/main/kotlin/blackjack/model/GameResult.kt
> +            Result.DRAW -> 0f
이번 미션에서는 참가자의 잔고를 나타내지 않고 베팅과 수익만 계산하고 있습니다.
베팅금으로 1000원을 투자한 경우를 생각해 보았습니다.
베팅금을 딴 경우 수익은 베팅금( * 1f)이 될 것이고, 베팅금과 함께 돌려받으니  유저의 잔고는 1000 + 1000으로 2000이 됩니다.
무승부로 베팅금을 그대로 돌려받은 경우는 수익 ( * 0f) 후 베팅금은 그대로 돌려받으니 유저의 잔고는 0 + 1000으로 1000이 됩니다. 여기서 잔고는 그대로 돌려받고 수익은 0원이라고 생각하였습니다. 
패배로 베팅금을 잃는 경우는 수익 (*-1f) 후 베팅금을 돌려받으니 유저의 잔고는 (-1000) + 1000 으로 0원이 됩니다. 여기서 잔고는 0원이 된다고 생각하였습니다.
위 세가지 상황에 대하여 정리하자면,
      베팅금 수익      잔고
승  1000  1000    2000
무  1000   0         1000
패  1000 -1000   0
출력 요구사항이 잔고가 아닌 수익출력이라, 수익을 0원처리 했는데 이것은 틀린 것일까요?

2024-03-16 10:25 UTC, jinuemong commented on src/test/kotlin/blackjack/model/BettingPayoutTest.kt
> +        val gameResult = gameManager.calculateGameResult()
이건 궁금한게 있습니다.
테스트를 위해서 gameManager, gameResult를 생성하였습니다.
하지만 gameManager, gameResult에 대한 테스트는 진행하지 않고, 
revenues에 대한 테스트를 진행하기 위해 `생성`하였습니다.
이게 잘못 된 것인가요?
만약 그렇다면 gameManager 테스트에서 딜러나 플레이어, participants를 생성하는 것,
gameResult 테스트에서 참가자들을 생성하고 gameManager를 생성하는 것도 잘못 된 테스트인 것 일까요?
테스트를 위해서 생성하는게 중복 테스트로 이어지는 것인지 궁금합니다..

2024-03-16 11:05 UTC, jinuemong commented on src/main/kotlin/blackjack/model/BlackJack.kt
> +        when (handCard.getGameScoreWithAceCount()) {
리뷰를 확인하고 이 코드에 대하여 많은 고민을 하게 되었습니다.
제가 코드를 설계하면서 생각한 부분은 에이스 여부를 외부로 유출하지 않고 score를 반환하자였습니다.
실제로 함수의 깊이가 깊어져서 아쉬움이 남는 것은 사실이지만, 전환 된 score를 반환하고 있기 때문에
외부에서는 에이스의 포함 여부를 알 수 없지 않을까라는 생각을 하게 되었습니다.
물론 updateGameStateWithScore() 내부에서가 아닌 단순히 getGameScoreWithAceCount()를 호출하게 된다면 score의 차이를 보고 에이스의 여부를 추측할 수 있게 됩니다.
하지만 getGameScoreWithAceCount()는 오직 updateGameStateWithScore() 내부에서만 활용되고 있고, 오히려 에이스의 여부를 필요한 순간 확장성을 너무 닫아둔 것은 아닌가하는 생각을 하게 되었습니다.
어떤 코드가 좋은 코드인지는 확실하게 알 수 없지만, 제가 작성한 코드에 의문점이 드는 것은 사실입니다.
하지만 더 좋은 방법으로 리팩토링을 시도하였으나, 그 역시 좋은 코드인지는 고민하게 됩니다..
이번 미션에서 저에게 가장 어려웠던 점 2가지가 이 코드에 그대로 들어나는 것 같습니다.
```
1. 어디까지 확장성을 열어두어야 할까?
2. 어디까지 외부에서 코드를 사용할 수 없도록 확장에 닫아야 할까?
```

2024-03-16 11:10 UTC, jinuemong commented
[2단계 4차 리팩토링] 이번에는 코드 수정이 많지 않게 되었습니다.
함께 고민해봤으면 할 부분을 코맨트로 달아봤어요!
몇가지는 코드를 수정하는 것보다 좀 더 의논하고 결정하는게 좋다고 판단하였습니다.
2단계 미션 끝까지 잘 부탁드립니다..🙇‍♂️🙇‍♂️

2024-03-16 15:31 UTC, laco-dev requested changes
고민하신 내용에 맞춰 기준을 잘 잡고 계신 것 같네요.

다만 서로 바라보는 방향이 달라서, 의견이 조금 충돌이 있는 것 같습니다.
조금 더 보충해서 답변 달아두었습니다 🙏🏻

2024-03-16 15:31 UTC, laco-dev commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        OutputView.outputPlayersCurrentHandCard(players)
> 요구사항을 만족하기 위해서 로직을 분리하는 것이 아닌 각 카드들을 무조건 2장씩 공개하고 출력할 때만 한 장만 출력하라는 말씀이신가요?
그럼 딜러와 플레이어로 굳이 나누는 이유는 뭐가 있을까요?

추상화가 되어있지 않나요??
참가자가 최초에 뽑은 카드가 몇 장인지 알 필요가 전혀 없어졌어요.
그렇기에 출력할 때 딜러와 플레이어를 다시 명시할 필요가 없다고 생각했어요.

> 오히려 일관성을 유지하기 위해서 participants로 전환하고, 이로 인해서 출력 시 딜러가 첫 번째 출력으로 나오지 않는다면 이것은 뷰의 일관성을 해치는 것은 아닐까요?.. 코드를 고치면서 생각이 많아집니다..

적어주신 이 내용으로 딜러를 명시적으로 먼저 출력하게 만들기 위함이라는 것으로 조금 이해가 되었습니다.

처음 느꼈던 생각은 딜러와 플레이어가 가지고 있는 카드를 출력하기 위해 동일한 출력물인데, 로직이 복잡하게 만들어져서 의견을 드렸습니다.

코드 두줄이면 해결될 것 같은데 왜 복잡하게 만들어졌지???
```kotlin
val participants: List<Participant> = dealer + players.toList()
OutputView.outputCurrentHandCard(participants)
```

2024-03-16 15:31 UTC, laco-dev commented on src/main/kotlin/blackjack/model/BlackJack.kt
> +        if (checkDrawState()) {
마이너한 의견인데요.
`checkXXX()` 라는 이름을 정말 좋아하시는군요..

그런데 그거 아시나요?
`check(...)` 라는 코틀린 함수는 반환하는 대신 오류를 터트린 다는 것을

2024-03-16 15:31 UTC, laco-dev commented on src/main/kotlin/blackjack/model/BlackJack.kt
> +        when (handCard.getGameScoreWithAceCount()) {
우... 너무 어렵게 생각하고 계신 것 같아요 😓 

에이스 카드가 카드뭉치에 있는지 없는지는 블랙잭 상태가 알 필요가 있는 것일까요?
카드뭉치는 점수를 계산하는 역할만 하면 되는데, 에이스 포함 여부를 외부에서 판단할 이유가 무엇인지 이해가 잘 안되요.

왜 아래 두개의 함수가 존재해야 하는지가 궁금한거에요.
```kotlin
getGameScoreWithAceCount()
getGameScoreWithoutAceCount()
```

또한, 블랙잭 상태는 철저하게 블랙잭에서만 관심을 가지게 만들었는데, 
`checkStateWithCardCount()` 라는 함수가 왜 상태라는 관심사를 뺏어올라고 하는것인지 모르겠어요.

카드뭉치가 무슨 상태이고 갯수인지는 관심없이, 상태는 내가 판단할태니 너는 2개인지 21점인지만 알려주면 되는게 아니었을까요?


```
카드 뭉치
- 카드를 가진다
- 카드의 점수를 계산한다
- 블랙잭 상태가 될 수 있는지 여부를 반환한다 (????)
- 에이스 카드가 있을 때 카드의 점수를 계산한다 (????)

블랙잭
- 카드와 협력하여 자신의 상태를 결정한다.
- ...
```


혹시 제가 잘못 이해하여서 핸드카드도 블랙잭 상태랑 강하게 결합시키려는게 목적이었다면 알려주세요. 그에 맞춰서 다시 판단하도록 하겠습니다. 😭

2024-03-16 15:31 UTC, laco-dev commented on src/main/kotlin/blackjack/model/GameResult.kt
> +            Result.DRAW -> 0f
출력 결과가 내용을 충분히 담고 있지 않아서, 이거는 생각하신 기준에 맞다면 자유에 맞기도록 하겠습니다..

저도 옜날에 미션을 구현할 때 똑같은 질문을 했거든요.
위에 의견은 고치라는 의미라기보다는 궁금해서 물어봤습니다

2024-03-16 15:31 UTC, laco-dev commented on src/main/kotlin/blackjack/model/CardDeck.kt
> +    fun generateCardDeck()
`generateCardDeck` 메소드가 인터페이스로 드러날 이유가 있는건가요??

2024-03-16 15:31 UTC, laco-dev commented on src/main/kotlin/blackjack/model/ShuffleCardDeck.kt
> +class ShuffleCardDeck(private val cards: Queue<Card> = LinkedList()) : CardDeck {
이 객체가 만들어졌다면, 테스트에서는 덱을 가짜 데이터로 준비해서 더 쉽게 만들어 볼 수 있을 것 같네요!

2024-03-17 02:00 UTC, jinuemong commented on src/main/kotlin/blackjack/model/BlackJack.kt
> +        if (checkDrawState()) {
마이너하지 않고 정확한 지적인 것 같아요.
check라는 뜻이 범위가 넓어서 사실 함수명 짓기 귀찮아서 때려넣는? 느낌이 있네요.
이전에 사용한 UserInformation이랑 비슷한 것 같아요.
어느정도 고민해서 전부 수정해봤습니다.

2024-03-17 02:05 UTC, jinuemong commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        OutputView.outputPlayersCurrentHandCard(players)
아무래도 제가 작성한 코드들이 출력함수, 변수명 등이 이해하기 어려운 것 같습니다.
이러한 것들이 코드를 이해하는데 혼란을 드린 것 같군요.
좀 더 명확하게 하도록 하는 연습이 필요할 것 같아요😭

2024-03-17 02:09 UTC, jinuemong commented on src/main/kotlin/blackjack/model/CardDeck.kt
> +    fun generateCardDeck()
CardDeck은  `generateCardDeck`을 통해서 내부를 초기화한다.
라는 생각으로 드러냈었습니다.
하지만 설계 의도에 따라서 달라질 수 있고, 클래스의 주된 책임이 아니라고 생각해서 수정했습니다.

2024-03-17 02:56 UTC, jinuemong commented on src/main/kotlin/blackjack/model/BlackJack.kt
> +        when (handCard.getGameScoreWithAceCount()) {
제가 코드를 꼼꼼히 보면서 생각해봤는데, 이것 역시 함수명이 혼란을 야기한 것 같습니다.
getGameScoreWithoutAceCount()는 제 코드에서 getTotalCardsSum()이 그 역할을 하고 있습니다. 함수의 기능을 분리하기 위해서 작성한 함수에요.
getGameScoreWithAceCount()는 Ace 상태를 고려한 게임의 총 스코어 입니다.
결국 외부에서는 getGameScoreWithAceCount()만 사용하고 있습니다.
네이밍을 getGameScore()로 변경해서 코드를 다시 보게 되었습니다.
getGameScoreWithoutAceCount()의 역할을 하는  getTotalCardsSum()은 단순히 계산함수,
getGameScoreWithAceCount()의 역할을 하는 getGameScore()은 에이스 여부를 가지고 총 점수를 계산하는 함수로 생각해봤습니다.
함수명을 변경하여 말씀하신 문제를 인지하고 어느정도 해결할 수 있었던 것 같습니다.
`핸드카드도 블랙잭 상태랑 강하게 결합시키려는게 목적`을 말씀해 주셨는데,
이는 어느정도 맞을지도 모르겠습니다.
처음 객체를 생성할 때 요구사항의 3가지 이상의 생성자를 사용하지 않는다에 너무 몰입하여 객체를 설계한 것 같아요.
머릿속으로는 블랙잭 = (핸드카드와 상태를 가지는 블랙잭)으로 강하게 결합시키고 함수를 설계한 것 같습니다.

2024-03-17 03:04 UTC, jinuemong commented
[2단계 5차 리팩토링]
- 함수명으로 인한 문제가 많아서 코드를 쭉 보면서 리팩토링을 진행해봤습니다.
- 함수명 수정으로 의도를 명확히 드러내고, 어느정도 수정이 이뤄졌습니다.

2024-03-17 14:20 UTC, laco-dev requested changes
좋습니다. 
사람마다 기준과 방향은 모두 다르지만 공통적으로는 객체는 코드를 통해 자신의 의도를 최대한 나타내는 목표를 가집니다.

마지막으로 테스트 코드 관련해서 의견을 남겨두었고 이 부분만 정리되면 미션 마무리 하도록 하겠습니다.

2024-03-17 14:20 UTC, laco-dev commented on src/test/kotlin/blackjack/model/BettingPayoutTest.kt
> +    }
이 테스트도 Result를 테스트하는 것이 아닐까요?

2024-03-17 14:20 UTC, laco-dev commented on src/test/kotlin/blackjack/model/BettingPayoutTest.kt
> +        val gameResult = gameManager.calculateGameResult()
> 이건 궁금한게 있습니다.
테스트를 위해서 gameManager, gameResult를 생성하였습니다.
하지만 gameManager, gameResult에 대한 테스트는 진행하지 않고,
revenues에 대한 테스트를 진행하기 위해 생성하였습니다.
이게 잘못 된 것인가요?
만약 그렇다면 gameManager 테스트에서 딜러나 플레이어, participants를 생성하는 것,
gameResult 테스트에서 참가자들을 생성하고 gameManager를 생성하는 것도 잘못 된 테스트인 것 일까요?
테스트를 위해서 생성하는게 중복 테스트로 이어지는 것인지 궁금합니다..
만약 수정해야 하는 사항이면 테스트 코드를 전부 수정하는 것을 고려하고 있습니다.

테스트를 위해 생성하는 것은 당연합니다.
그런데 지금 테스트는 목적과 구현이 서로 일치하지 않아요.

게임 결과가 만들어낸 Revenue를 테스트 하고 싶은건데 게임 매니저가 왜 등장하는건가요???

우선 이 이야기 이전에 BettingPayoutTest 라는 것이 왜 있는지 모르겠어요.

GameManager는 calculateGameResult() 메소드를 통해 만들어진 GameResult를
GameResult는 calculateRevenuePercentages() 메소드를 통해 만들어진 Revenue를 테스트 하는게 아닌가요?

단위 테스트에서는 테스트하려는 대상에만 집중하기 때문에 불필요한 관심사는 배제하는게 우선입니다.

2024-03-17 14:20 UTC, laco-dev commented on src/test/kotlin/blackjack/model/BettingPayoutTest.kt
> +    fun `(딜러 블랙잭 , 플레이어 블랙잭 ) 정상적인 Payout과 수익금 테스트`() {
테스트 코드는 프로그램의 사양서라고도 부릅니다.
그만큼 기능이 최대한 구체적이고 직관적으로 드러나도록 작성되어야 한다는 의미를 뜻하는데요.

이 테스트에서 "정상적인"이 의미하는게 무엇인가요?
테스트 코드만 보고도, 수익금이 어떻게 계산되는지 알 수 있을까요?
만약 구현 코드를 잘못짰는데 우연히 통과한다면 정상인건가요?

> 딜러와 플레이어가 모두 블랙잭일 때 배팅 금액이 50원이라면 수익금은 0원이다.
> 플레이어가 버스트라면 딜러 패와 상관없이 수익금은 0원이다.
> 플레이어와 딜러가 동점이라면 수익금은 0원이다.
> 플레이어가 블랙잭으로 승리했을 때 배팅 금액이 100원이라면 수익금은 1.5배인 150원이다.
...

2024-03-17 14:20 UTC, laco-dev commented on src/test/kotlin/blackjack/model/BettingPayoutTest.kt
> +            )
프로덕션 코드와 달리 테스트 코드에서는 하드 코딩이나 여러가지 전략을 이용해, 최대한 불필요한 코드를 줄이고는 합니다.

가령 딜러와 플레이어를 생성하는 코드가 불필요하게 반복된다면 함수를 분리해서 만들어 낼 수도 있습니다.
https://blog.kotlin-academy.com/item-30-consider-factory-functions-instead-of-constructors-e1c747fc475

```kotlin
val player = Player("7 to 다이아몬드", "7 to 클로버")
val dealer = Dealer("7 to 스페이드", "7 to 하트")
val participnat = Participant(player, dealer)
...
```

2024-03-17 18:30 UTC, jinuemong commented
[2단계 6차 리팩토링]
안녕하세요 리뷰어님 어쩌면 제가 고민한 부분들이 리뷰어님을 피곤하게 만들었는지도 모르겠습니다.
하지만 이해가 되지 않는 부분을 빠르게 미션을 완수하고 싶다는 이유로 그냥 넘어가고 싶지 않았습니다.
리뷰어님 덕분에 이번 미션을 통해서 성장했다고 생각합니다.
함께 끝까지 이끌어주셔서 감사해요.
마지막 질문으로는 참고해주신 자료를 보고 불필요하게 반복되는 코드를 줄이기 위해서
createPlayerWithCards(), createDealerWithCards() 함수를 생성했는데요.
이 함수들을 Utils라는 파일에 담아두었지만 테스트 패키지에 두어도 되는지 고민이 됩니다.
테스트 코드만을 위한 함수라 생각하여 테스트 패키지에 두었는데 어떻게 생각하시나요?

2024-03-18 10:59 UTC, laco-dev approved these changes
고생 많으셨습니다.

그동안 많이 귀찮고 힘들게 한 것 같은데 잘 따라와 주셔서 감사합니다.
아쉬우셨던 점도 있고, 좋았던 점도 있으셨을텐데요.

앞으로 남은 미션에서 지금까지 배운 내용들을 통해 더욱 성장 하시기를 기대하겠습니다.

2024-03-18 10:59 UTC, laco-dev commented on src/test/kotlin/blackjack/model/RevenueTest.kt
> +    fun `딜러 lose , 플레이어 블랙잭인 상황에서 수익금은 150원이어야 한다`() {
이렇게만 작성해두면 배팅금액이 얼마인지 상관없이 수익금은 항상 150원이다.
 처럼 보일 수도 있겠네요. :)

2024-03-18 10:59 UTC, laco-dev commented on src/test/kotlin/blackjack/model/Utils.kt
> +}
> 마지막 질문으로는 참고해주신 자료를 보고 불필요하게 반복되는 코드를 줄이기 위해서
createPlayerWithCards(), createDealerWithCards() 함수를 생성했는데요.
이 함수들을 Utils라는 파일에 담아두었지만 테스트 패키지에 두어도 되는지 고민이 됩니다.
테스트 코드만을 위한 함수라 생각하여 테스트 패키지에 두었는데 어떻게 생각하시나요?

이러한 개념을 fixture라고 부르는데요.
마침 크루 한분이 좋은 자료를 올려주셨기에 답변을 대신해봅니다.
https://velog.io/@langoustine/Test-Fixture

2024-03-18 10:59 UTC, merged