[블랙잭] 에디 2단계 미션 제출합니다.
woowacourse/kotlin-blackjack pull request #93
Opened 2024-03-14 17:35 UTC by junjange

1단계 리뷰 반영과 2단계 미션 구현했습니다!!

2024-03-15 17:01 UTC, malibinYun requested changes
2단계 미션 고생 많으셨어요.
고민해보면 좋을 점들에 코멘트 남겨두었어요.
충분히 고민 해보신 뒤 피드백 반영해주세요!

2024-03-15 17:01 UTC, malibinYun commented on src/main/kotlin/blackjack/model/GameDeck.kt
>      }
if - else 를 활용하는 것이 가독성에 더욱 도움이 되는 경우가 많아요.

또, 이런 형태를 잘못 사용하게 된다면 let 블럭과 run 블럭 모두가 실행되는 말도 안되는 상황이 발생할 수도 있어요.
let 스코프 함수 내부에 잘못된 코드를 작성했을 때 발생하게 되겠는데요,
어떤 경우에 두 스코프가 다 실행 될 수 있을지 고민해보시면 좋겠어요!

그리고 이 함수가 단일 책임 원칙을 지키고 있는지도 고민해보세요 :)

2024-03-15 17:01 UTC, malibinYun commented on src/main/kotlin/blackjack/model/GameDeck.kt
>      }
53번쨰의 카드를 뽑았을 때 원하는 카드가 나오는지 테스트할 수 있는 함수일까요?

2024-03-15 17:01 UTC, malibinYun commented on src/main/kotlin/blackjack/model/GameResult.kt
> +    data object Draw : GameResult
enum class와 어떤 점이 차이가 있었나요?

2024-03-16 01:44 UTC, junjange commented on src/main/kotlin/blackjack/model/BetAmount.kt
> +        fun from(value: String): BetAmount {
배팅 금액에 대한 유효성 검증 이후, 문자열을 파싱하는 것은 도메인 역할이라고 생각했습니다!

2024-03-16 01:50 UTC, junjange commented on src/main/kotlin/blackjack/model/Card.kt
> +        }
네네!! 수정하겠습니다! c0d0c2044319a1cfd7eec9816ec14cc94c9a807b

2024-03-16 02:08 UTC, junjange commented on src/main/kotlin/blackjack/model/CardHolder.kt
> +    ) {
모를 것 같습니다.. 수정하도록 하겠습니다! 09a92b8f86d1f1257b58a714f1d5b5583933ba3c

2024-03-16 02:31 UTC, junjange commented on src/main/kotlin/blackjack/model/CardHolder.kt
> +    }
넵넵!! 15e1e77c0535b029e7e0dc2ee85731108c106794

2024-03-16 02:37 UTC, junjange commented on src/main/kotlin/blackjack/model/GameResult.kt
> +    data object Draw : GameResult
profit 함수에서 sealed interface를 통해 패턴 매칭을 할 때, 컴파일러가 타입 안정성을 유지하면서 코드를 검증하여 개발 과정에서 실수를 안 할 수 있는 장점이 있었습니다.

2024-03-16 04:53 UTC, junjange commented on src/main/kotlin/blackjack/model/GameDeck.kt
>      }
```
fun main() {
    var test: Int? = 1

    test?.let {
        println("let 실행됨")
        test = null
        null
    } ?: run {
        test = 1
        println("run 실행됨")
    }

    println(test)
}
```

let과 run 블럭 모두 실행되는 경우가 위 상황처럼 let에서 null을 반환하는 경우일까요?!
위같은 오류가 발생할 수 있다고 판단하여 수정했습니다! 메서드 분리도 함께 진행했습니다! 90626bb58d2f8be3de1f72c5425e1e5c6429ca17

2024-03-16 04:53 UTC, junjange commented on src/main/kotlin/blackjack/model/GameDeck.kt
>      }
테스트 하지 못할 것 같습니다! 테스트할 수 있도록 수정했씁니다!!

2024-03-16 05:36 UTC, junjange commented on src/main/kotlin/blackjack/model/Card.kt
>          fun of(value: List<Pair<Pattern, CardNumber>>): List<Card> {
팩토리 메서드에서 from은 주어진 정보를 통해 해당 객체를 반환하고 of는 해당 객체를 포함하는 새로운 컬렉션을 제공하는 것으로 이해하고 위처럼 구현했습니다! 그러나 다른 개발자가 명확히 알 수 없을 것으로 판단하여 수정했습니다! 인스턴스 캐싱 부분도 함께 수정했습니다! b2f1b801713e0c1d4361600f28c533f5478a04c2

2024-03-16 05:59 UTC, junjange commented on src/main/kotlin/blackjack/model/CardHolder.kt
네네!! 디미터의 법칙을 준수하면서 리팩터링을 진행했습니다! 98299dd5b1da4618c7c8779675448a55c9de7d58

2024-03-16 07:01 UTC, junjange commented on src/main/kotlin/blackjack/model/CardHolder.kt
> +        val gameResult = (blackjackState as Finished).calculate(this, opponent)
부모와 자식간에 결합도가 증가하여 유지보수가 힘들어질 것 같습니다! 단일 책임 원칙도 위반 될 것으로 보입니다! 의존성을 제거하고 코드를 간소화했습니다! efa1571899fcb742072978618427a836f55f0482

2024-03-17 05:25 UTC, malibinYun requested changes
피드백 반영 고생하셨어요.
생각해보면 좋을 점들에 코멘트 남겨두었어요.
피드백 반영 후 다시 리뷰 요청 부탁드려요!

2024-03-17 05:25 UTC, malibinYun commented on src/main/kotlin/blackjack/model/Card.kt
> +            return newCards.toList()
이부분은 mutable collection을 생성해서 채워넣는 방법 말고, 메서드 체이닝으로 한 번에 컬렉션을 만들어낼 수 있어보여요 :)
다양한 코틀린 컬렉션 함수를 활용해서 메서드 체이닝을 연습해보셔도 좋겠어요.

2024-03-17 05:25 UTC, malibinYun commented on src/main/kotlin/blackjack/model/Card.kt
> +        fun createDeck(): List<Card> = cards
create라는 이름으로 무언가 새로운 인스턴스를 생성할 것 처럼 느껴지네요.
companion object 의 card를 직접 접근하는 것과 어떤 차이점이 있는지 모르겠어요.
전체적으로 필요하지 않은 코드들을 다듬어 덜어내는 연습을 해보세요 :)

2024-03-17 05:25 UTC, malibinYun commented on src/main/kotlin/blackjack/model/CardHolder.kt
> +sealed class CardHolder(val userInfo: UserInfo) {
open, sealed, abstract 혹은 interface 중 어떤 것이 적절한 사용일지 충분히 고민해보셔도 좋겠어요.

2024-03-17 05:25 UTC, malibinYun commented on src/main/kotlin/blackjack/model/CardHolder.kt
>      }
코틀린의 프로퍼티 문법을 활용해보세요 :)

2024-03-17 05:25 UTC, malibinYun commented on src/main/kotlin/blackjack/model/CardHolder.kt
> +        gameDeck: GameDeck,
플레이어가 덱에 대한 관심을 가지고 있어야할 지 고민해보세요 :)

2024-03-17 05:25 UTC, malibinYun commented on src/main/kotlin/blackjack/model/CardHolder.kt
> +    fun getSumOfCards(): Int = blackjackState.calculateHand()
`카드의 합산 가져오기` `손계산하기` 이 둘에 대한 이름은 한 단어를 가리키기도 하네요.

`냄비에물550ml를넣고빨간가루가들어있는손바닥만한봉투를뜯어물에뿌린다음100도씨까지올려서건조된밀가루무언가를넣고3분간기다린다`
라는 이름보다,
`라면 끓이기`
라는 이름을 지어보는 연습을 해보세요 :)

2024-03-17 05:25 UTC, malibinYun commented on src/main/kotlin/blackjack/model/Dealer.kt
shouldDrawCard() 이 친구는 CardHolder, Dealer, Player 모두가 갖고있는 듯한 느낌이 드네요!
공통으로 갖고있는 멤버지만, 실행했을 때 동작은 다르게 만드는 방법이 있을까요?

2024-03-17 05:25 UTC, malibinYun commented on src/main/kotlin/blackjack/model/DeckManager.kt
> +}
가장 랜덤의 요소를 줄일 수 있는 것을 찾아 그것을 구현의 요소로 가져가면 좋겠어요.
결국 랜덤 카드를 뽑는 것이 랜덤의 요소이니, 카드 한 장을 가져오는 메서드를 인터페이스로 만들어볼 수 있겠어요.

reset등은 결국 외부에서 이 객체를 제어하는 느낌이 강해, 객체 간 협업을 한다는 느낌을 주긴 어려워보여요.

카드 한 장을 주는 인터페이스를 만들었으니, 하위 구현은 매우 간단하게 진행해볼 수 있겠지요.
52장만이 있어서, 53번째부터는 exception을 발생시킬수도,
내맘대로 구성된 순서의 카드를 뽑는 구현이 있을수도,
52장을 다 사용하면 알아서 다음 카드를 주는 무한 구현체가 있을수도.

랜덤의 요소를 최소한으로 줄여보시면 좋겠어요!

2024-03-17 05:25 UTC, malibinYun commented on src/main/kotlin/blackjack/model/GameResult.kt
> +    data object Draw : GameResult
> 패턴 매칭을 할 때, 컴파일러가 타입 안정성을 유지하면서 코드를 검증하여 개발 과정에서 실수를 안 할 수 있는 장점이 있었습니다!

enum은 말씀해주신 위 장점이 존재하지 않았나요?

2024-03-17 05:25 UTC, malibinYun commented on src/main/kotlin/blackjack/state/BlackjackState.kt
> +interface BlackjackState {
BlackjackState 와 Blackjack은 처음 보는 개발자들이 서로 어떻게 다른 객체인지 내부 구현을 자세히 보지 않고 파악할 수 있을까요?

2024-03-17 05:28 UTC, malibinYun commented on src/main/kotlin/blackjack/model/GameDeck.kt
>      }
네! 맞아요. 생각보다 null을 반환하는 메서드들이 꽤나 많답니다.
특히 java의 메서드가 non-null 이라고 착각했을 때 자주 발생하게 되지요.

지금은 예시 코드를 작성하시면서
"무슨 이런 말도안되는 일이 발생할까? 너무 방어적인것 아닐까?"
하는 생각이 드실 수 있겠지만,
생각보다 자연스러운 코드인데도 이런 현상이 발생해버린다면, 디버깅할때 굉장히 골치아파진답니다. 코드는 자연스러운데, 실행은 비정상적이니, 원인을 찾아내는 데 굉장히 어려워지게돼요.

2024-03-17 07:13 UTC, junjange commented on src/main/kotlin/blackjack/model/Dealer.kt
흠 공통으로 갖고 있어서 interface를 통해 추상화하려고 했지만.. Dealer의 shouldDrawCard는 본인의 카드 점수 합에 따라서 값이 달라지고 Player의 shouldDrawCard는 사용자의 입력에 따라서 달라지기 때문에 추상화가 쉽지 않은 것 같습니다!

2024-03-17 07:20 UTC, junjange commented on src/main/kotlin/blackjack/model/Card.kt
> +            return newCards.toList()
네네!! 감사합니다!! 8f904cf02560e2cab2de22a6781acb46ecbb660b

2024-03-17 07:20 UTC, junjange commented on src/main/kotlin/blackjack/model/Card.kt
> +        fun createDeck(): List<Card> = cards
헉 지금 다시보니 중복되는 내용이네요ㅠㅠ 감사합니다!! 0d2b950945ae4d9688776ceec563f05328f0b933

2024-03-17 07:25 UTC, junjange commented on src/main/kotlin/blackjack/model/CardHolder.kt
> +    fun getSumOfCards(): Int = blackjackState.calculateHand()
넵넵!! 감사합니다!!

2024-03-17 07:41 UTC, junjange commented on src/main/kotlin/blackjack/model/DeckManager.kt
> +}
헉 이해했습니다!! 다음과 같이 position으로 아규먼트를 받으면 카드덱에서 카드를 뽑을 수 있게 구현했습니다! 90371c88ac0ce8619f475436c56ae6e1f48356b6

2024-03-18 02:27 UTC, malibinYun approved these changes
블랙잭 미션 고생 많으셨어요.
내일 부터 진행 할 미션은 매우매우 어려우니, 미션은 이만 마무리 짓도록 하겠습니다 :)
시간이 허락한다면 모든 미션들을 처음부터 다시 만들어보면서 연습을 해보셔도 좋겠어요!
처음과는 아예 다른 코드를 마주하게 될 거예요.
다른 미션들도 화이팅이에요!

2024-03-18 02:27 UTC, malibinYun commented on src/main/kotlin/blackjack/model/Card.kt
> +        }
이 함수도 필요에 의해 public으로 공개되어있는걸까요?

2024-03-18 02:27 UTC, malibinYun commented on src/main/kotlin/blackjack/model/DeckManager.kt
> +}
이전 피드백에 이어서,
기대한 인터페이스는 카드 단 한장만을 가져오는 메서드만 가진 인터페이스였어요.
```kotlin
interface ~ {
    fun getCard(): Card
}
```

랜덤의 요소를 최소화해본다 라는 것에 가장 많이 고민해보세요.
reset은 랜덤의 요소였을지, position은 랜덤의 요소였을지 연관지어서요!

1, 2 단계 미션에서 배운 것들을 완전히 자신의 것으로 만들어보세요 :)
미션을 모두다 다시 한 번 구현해보는 것도 좋은 방법이 될 거예요 🙂

2024-03-18 02:27 UTC, malibinYun commented on src/main/kotlin/blackjack/model/GameResult.kt
> +    data object Draw : GameResult
특별하게 장점을 살리고 있지 않다면, 저는 필요한 부분만 가져가는 것이 코드를 이해하는 데 불필요한 생각이 들지 않게 해준다 생각해요.
이렇게 할거면 왜 enum을 쓰지 않았지? 라는 의문을 들게하는 것 부터, 코드를 이해하는 데 벌써 한 번의 멈춤이 생겼다고 생각해요.
저는 최대한 필요에 의해 코드를 구성하는 것을 선호해요 :)

앞으로 어떻게 할 지는 에디의 선택이겠지만요 🙂

2024-03-18 02:27 UTC, malibinYun commented on src/main/kotlin/blackjack/model/Dealer.kt
입력을 받아오기 위한 람다 등은 최대한 깊이를 깊게 가져가지 않았으면 했어요.
게임을 관제하는 객체를 하나 만들어둔다면 이런 람다를 도메인 깊이 알지 않을 수 있으니까요.
그래서 처음에 달아둔, https://github.com/woowacourse/kotlin-blackjack/pull/61#discussion_r1520994502 이 피드백을 남겨두기도 했었지요!
그렇다면 플레이어나 딜러나 그저 카드를 받기만 할 수 있는 객체가 되고, 줄 지 말 지는 게임 객체가 판단해줄 수도 있었겠지요!
추상화를 활용한다면 최대한 공통의 요소를 뽑아내려 고민을 많이 해보세요 :)

2024-03-18 02:27 UTC, malibinYun commented on src/main/kotlin/blackjack/state/BlackjackState.kt
> +interface BlackjackState {
앗 ㅋㅋㅋ
아래 피드백을 다시 곱씹어볼까요 ?_?
https://github.com/woowacourse/kotlin-blackjack/pull/61#discussion_r1521025533

2024-03-18 02:28 UTC, merged

2024-03-18 07:11 UTC, junjange commented on src/main/kotlin/blackjack/model/Card.kt
> +        }
외부에서 따로 Card를 확인할 것 같아 public으로 구현했지만, 현재는 사용하지 않기에 private으로 바꿔야할 것 같습니다!

2024-03-18 07:28 UTC, junjange commented on src/main/kotlin/blackjack/model/DeckManager.kt
> +}
랜덤의 요소를 최소화하는 것에 대해서 좀 더 고민해보겠습니다!..

2024-03-18 07:29 UTC, junjange commented on src/main/kotlin/blackjack/model/GameResult.kt
> +    data object Draw : GameResult
저도 말리빈처럼 왜라고 말했을 때 답하는 것을 중요시하는데 위 부분에서 sealed class의 장점을 살리지 못한다면 enum으로 수정해야할 것 같습니다!

2024-03-18 07:31 UTC, junjange commented on src/main/kotlin/blackjack/model/Dealer.kt
저도 그것에 대해서 고민이 많았고 해결하고 싶었지만 해결하지 못했네여ㅠㅠ 좀 더 고민해보겠습니다! 감사합니다!!