[블랙잭] 올리브 2단계 미션 제출합니다.
woowacourse/kotlin-blackjack pull request #97
Opened 2024-03-16 18:40 UTC by kimhm0728

안녕하세요 파이로! 이번 리뷰도 잘 부탁드립니다.
시간 분배를 제대로 못해서 PR 제출이 늦었네요 😢 
DM으로 조급해하지 않아도 된다고 해주셔서 감사했습니다..!

## 질문 or 기능 구현 외의 주요한 리팩터링
1. step1에서 `Lazy Calculation`이라는 키워드를 [알려주셨는데요](https://github.com/woowacourse/kotlin-blackjack/pull/72#discussion_r1518410948), step2의 수익 계산하는 로직에 적용해보았습니다.
< **기존 구현 커밋 ([adfbea1](https://github.com/kimhm0728/kotlin-blackjack/commit/adfbea1cf60cbe2bf225afee26a5e74fb7fdf813), [bee8e3f](https://github.com/kimhm0728/kotlin-blackjack/commit/bee8e3f95f1605ebd118c2459d16524af857e315))** >
처음에는 `Delaer`의 `profit()`를 호출하면 `Dealer`의 수익도 반환하고, `Player`의 수익도 계산하여 `Player`의 profit 프로퍼티를 초기화하도록 구현했습니다. 그런데 이 `Dealer`의 `profit()`이 한 가지 이상의 일을 하는 것이라고 생각했습니다. 또한 `Dealer`의 수익만 필요하고 `Player`의 수익은 필요하지 않은 경우에도, 모든 profit()이 계산되기 때문에 말씀해주신 `Lazy Calculation`를 떠올렸습니다..!
< **수정 커밋 ([f103b54](https://github.com/kimhm0728/kotlin-blackjack/commit/f103b545d3002228f93fb1ece29c05508f328ca9))** >
그래서 `Dealer`, `Player`에서 수익을 저장하는 프로퍼티는 따로 가지지 않고, `profit()`을 호출하면 자신의 수익만을 반환하도록 수정했습니다. 하지만 `Dealer`의 수익을 구할 때는 기존 코드처럼 `Player`의 수익을 구해서 마이너스 연산만 해주면 되는데, 오히려 코드량이나 연산이 더 많아졌다는 느낌이 들었습니다. 이에 대해 리뷰어님은 어떻게 생각하시나요? 제가 잘 리팩터링한 건지 잘 모르겠습니다..!! 올바른 접근 방법인지 궁금합니다!

2. step1 코멘트 중 해당 [코멘트](https://github.com/woowacourse/kotlin-blackjack/pull/72#discussion_r1524468814)는 아직 반영하지 못했습니다 🥲 저는 `Hand` 클래스 init 블럭 내에서 `initCard()`를 구현하는 것이 적절하다고 생각이 드는데, `initCard()`에서 두장의 카드를 뽑으려면 `CardProvider` 구현체가 필요합니다. 그런데 `CardProvider`를 `Hand`의 생성자 파라미터로 전달하기 위해서는, "Controller -> Players -> Player -> Role -> Hand"의 흐름으로 전달해주어야 합니다. 이를 여러번 시도해봤는데, 생성자나 함수의 파라미터 개수가 많아지고 코드가 너무 지저분해져서 결국 반영하지는 못했습니다.. 초기 설계 자체가 잘못된 것 같아서 미션 끝나면 처음부터 다시 구현할 생각도 하고 있는데요(ㅠㅠ) 이 부분 조언 부탁드릴 수 있을까요?  

3. step1에서 패키지에 대한 얘기를 해주셔서, step2를 진행하면서 적절한 패키지 구조에 대해 고민해보았습니다. 기존에는 `Hand`가 "플레이어나 딜러가 상태로 가지고 있는 클래스"이기 때문에 `participant` 패키지에 있는 것이 적절하다고 생각했습니다. 그런데 배팅 금액이나 수익을 나타내기 위해 사용되는 `Amount` 클래스가 추가되면서, `participant` 패키지에 `Hand`와 `Amount`가 있는 것이 코드를 처음 읽는 사람에게는 혼란을 줄 수 있겠다는 생각을 했습니다. 그래서 `participant` 패키지에는 `Player`나 `Dealer`처럼 "게임에 참여하는 사람" 관련 클래스만을 위치시켰습니다. **([4bd90a4](https://github.com/kimhm0728/kotlin-blackjack/commit/4bd90a4f86578ca586d3b6e30a2a469044452a7a))** 현재 `Hand`와 `Amount`의 상위 패키지는 model인데, 이처럼 model 내 클래스끼리 패키지 레벨을 통일시키지 않아도 되는지 궁금합니다!
(\+ card 패키지와 혼동을 막기 위해 `HandCards`를 `Hand`로 변경했습니다)

4. step1에서 카드 점수를 계산하는 기능에 대한 [코멘트](https://github.com/woowacourse/kotlin-blackjack/pull/72#discussion_r1521373750)를 달아주셨는데, 생각해보니 Ace가 11으로 계산되는 경우는 최대 한 번밖에 없더라구요. 그래서 `fold` 람다 내에 if를 여러개 작성하지 않고, Ace가 존재하는지 안 하는지만 검사하도록 [수정](https://github.com/kimhm0728/kotlin-blackjack/commit/54b1b19a712fe71f66eb16dfb22fc9b50df20693)했습니다.

5. 테스트 코드에 `Card.of(~~~, ~~~)`와 같은 코드가 반복되어 가독성이 좋지 않았습니다. 카드 생성에 대한 테스트 픽스처를 따로 구현해서 해결했습니다. 또한 `Hand`의 생성자 파라미터로 바로 cards가 들어갈 수 있도록 [수정](https://github.com/kimhm0728/kotlin-blackjack/commit/f27da2f8e02917b5145c7707af94cbe739c58c19)했습니다.

6. step1에 달아둔 [질문](https://github.com/woowacourse/kotlin-blackjack/pull/72#discussion_r1524384440) 링크 첨부합니다.

2024-03-17 01:29 UTC, ghojeong commented
6. 첨부한 링크에 답변 완료했습니다. 패키지 구조는 [안드로이드 공식 샘플 프로젝트](https://github.com/android) 를 참고하는 습관을 가지면 좋습니다.

2024-03-17 04:46 UTC, ghojeong requested changes
올리브!
블랙잭 미션에서는 가독성을 헤치는 연속된 조건분기를 없애기 위해,
디자인패턴이나 객체 설계를 조언드리게 되는데,
특별한 디자인패턴 키워드 없이도 연속된 if 문들을 무척 잘 없애주신 것 같습니다. 👍

질문주신 내용에 대해 답변을 남겨보았는데, 현재 고민하고 계신 문제들을 해결하는데 도움이 되었으면 좋겠습니다.
혹시 추가의견이 필요하시면 언제든 편하게 DM 주세요!

2024-03-17 04:46 UTC, ghojeong commented on src/main/kotlin/blackjack/model/participant/Player.kt
>          }
> `CardProvider`를 `Hand`의 생성자 파라미터로 전달하기 위해서는, "Controller -> Players -> Player -> Role -> Hand"의 흐름으로 전달해주어야 합니다. 이를 여러번 시도해봤는데, 생성자나 함수의 파라미터 개수가 많아지고 코드가 너무 지저분해져서 결국 반영하지는 못했습니다.. 초기 설계 자체가 잘못된 것 같아서 미션 끝나면 처음부터 다시 구현할 생각도 하고 있는데요(ㅠㅠ) 이 부분 조언 부탁드릴 수 있을까요?  

지금은 `Player -> Role -> Hand`  대신에, `Player -> Card` 로 CardProvider 를 넘기고 있군요.
CardProvider 가 Card 의 리스트를 제공함에도,
다시 또 Card 가 CardProvider 를 호출하는 static 함수를 가지는 것은 쌍방향으로 의존성이 생기는 것 같아서 요상해보입니다.

처음부터 다시 구현해보시겠다고 하셨는데, 저는 무척 환영합니다.
저도 그럴 필요성을 동의합니다.
그에 대한 저의 조언은 현재 companion object 안에 있는 static 함수 중, of 나 from 같은 기본적인 팩토리 함수 외에,
모든 static 함수들을 static 이 아니게 될 수 있도록 적절한 객체에게 할당을 해보시라고 조언드리고 싶습니다.
static 으로 선언된 함수는 사실 어느 객체에 있어도 상관없는 유틸 함수라고 생각을 해주셔야 합니다.

2024-03-17 04:46 UTC, ghojeong commented on src/main/kotlin/blackjack/model/Amount.kt
> +    operator fun plus(other: Amount) = Amount(price + other.price)
> 현재 `Hand`와 `Amount`의 상위 패키지는 model인데, 이처럼 model 내 클래스끼리 패키지 레벨을 통일시키지 않아도 되는지 궁금합니다!

저의 개인적인 스타일을 말씀드리자면, 저는 여러 패키지에서 공통적으로 쓰이는 객체들은 `model.common` 이라고 해서,
common 패키지를 만들고는 합니다.
하지만 미션은 요구사항이 많지 않으므로 가능한 common 이 필요없게끔 객체 설계를 해주셨으면 합니다.
저는 혼란이 생길거라면 굳이 card 와 participant 패키지를 나누지 말고, Amount 와 Hand 가 있는 model 패키지로 다같이 묶어버리는게 낫지 않을까 생각이 들었습니다.

블랙잭 미션 완료까지 시간이 얼마 안 남았고 굳이 분류해야할만큼 model 객체가 많지 않으므로, 
다 같은 model 패키지로 묶어버리고 차라리 패키지보다는 객체설계 개선에 시간을 더 쓰는게 좋지 않을까 제안해봅니다.

2024-03-17 04:46 UTC, ghojeong commented on src/main/kotlin/blackjack/model/Hand.kt
> +        return _cards.any { it.isAce() } && total + Denomination.ACE_BONUS_SCORE <= burstCondition
> step1에서 카드 점수를 계산하는 기능에 대한 코멘트를 달아주셨는데, 생각해보니 Ace가 11으로 계산되는 경우는 최대 한 번밖에 없더라구요. 그래서 `fold` 람다 내에 if를 여러개 작성하지 않고, Ace가 존재하는지 안 하는지만 검사하도록 수정했습니다.

기존의 연속된 If 문보다 지금이 훨씬 보기편한 것 같습니다. 
람다에 집착하지 않고 함수 분리해주셔서 멋집니다. 👍

2024-03-17 04:46 UTC, ghojeong commented on src/test/kotlin/blackjack/model/TestFixtures.kt
> +const val DEFAULT_BATTING_AMOUNT = 1000
> 테스트 코드에 `Card.of(~~~, ~~~)`와 같은 코드가 반복되어 가독성이 좋지 않았습니다. 카드 생성에 대한 테스트 픽스처를 따로 구현해서 해결했습니다. 

테스트에 자주 쓰이는 인스턴스들을 미리 Fixture 로 만들어 주신 점은 좋습니다. 👍

2024-03-17 04:46 UTC, ghojeong commented on src/main/kotlin/blackjack/model/participant/Player.kt
> +        }
게임의 결과를 분기처리하는 핵심 로직에 대한 책임은 Role 이 가져가게 되었군요!
Role 의 로직을 super 의 형태로 재사용할 수 있도록 해주신 점 기발한 것 같습니다. 👍 
어찌보면 4개의 연속된 분기처리라서 가독성이 떨어질 수 있음에도, 분기조건을 가독성 좋은 함수명으로 분리해주셔서 코드를 읽기 수월해 진 것 같습니다.

2024-03-17 07:05 UTC, ghojeong commented
@kimhm0728 

6번 질문을 포함해 조언 드리고 싶은 부분이 있어 말을 드립니다.
"시간 분배를 제대로 못해서" 라는 말씀을 주셨는데,
그럴수록 제가 더 효율적으로 시간을 쓸 수 있도록, 작업 우선순위를 조언했었어야 했다는 생각이 드네요.

우테코의 모든 미션에서 제일 중요하게 시간을 써야할 부분은 "객체 설계" 입니다.
그리고 객체 설계를 위해서는 다음 요소에 시간을 써야만 합니다.

1. 객체의 "역할", "책임", 그리고 다른 객체끼리의 "협력"
2. Model 과 View 의 분리
3. Model 의 비즈니스 로직에 대한 테스트
4. 가독성

6번 질문에서 제가 `model.result` 를 처음 언급했던 것은,
패키지 설계를 고도화 해달라는 요청이 아니라,
model 안에 테스트 불가능한 객체가 있었고, 테스트 불가능한 영역이 커질까 우려되어 말씀을 드렸었습니다.

올리브께 답변을 드리다가 제가 비효율적인 방향으로 피드백을 드린 것 같아,
제 잘못을 바로 잡고 싶어 강하게 말씀드리게 되네요.
가령 테스트 관점에서 2단계에서 추가된 요구사항에 관한 테스트가 전혀 보이지 않습니다.

가령 주요 요구사항으로 "카드를 추가로 뽑아 21을 초과할 경우 배팅 금액을 모두 잃게 된다." 라는 내용이 있는데,
해당 비즈니스 로직이 정말 구현되었는지 테스트 코드만으로는 확인할 수가 없어서 직접 실행을 통해 확인을 해봐야합니다.

해당 분기는 Role 의 isBurst() 함수를 통해 이루어지고 있고,
그렇다면 해당 함수에 대한 테스트 코드가 존재해야 합니다.

모든 함수에 대해서 테스트를 작성할 필요는 없지만,
미션 요구사항을 만족하고 있는지 테스트만으로도 어느정도 알 수 있도록,
테스트에 시간을 투자해주시면 감사하겠습니다.

2024-03-17 09:02 UTC, kimhm0728 commented on src/main/kotlin/blackjack/model/participant/Dealer.kt
> +            else -> super.gameResult(player)
확실히 이전 코드보다는 함수의 역할이나 반환값이 명확하다고 느껴졌습니다. 그런데 아직 이런 리팩터링 과정에 익숙치 않아서, 제 방식이 적절한지 확신이 들지는 않는 것 같아요.. 계속 비슷한 연산이 반복되는 것에 대해 걱정하게 되네요. ㅋㅋ 블랙잭 미션처럼 작은 프로젝트에서는 연산이 많아지는 것보다 유지보수성에 대한 고민이 훨씬 중요하겠네요!! 감사합니다 파이로 😀

2024-03-17 09:22 UTC, kimhm0728 commented on src/main/kotlin/blackjack/model/participant/Player.kt
>          }
> CardProvider 가 Card 의 리스트를 제공함에도,
다시 또 Card 가 CardProvider 를 호출하는 static 함수를 가지는 것은 쌍방향으로 의존성이 생기는 것 같아서 요상해보입니다.

Card의 불필요한 생성을 막기 위해 생성자를 private으로 제한해두고, Card의 companion obejct 내에서 생성할 수 있는 모든 카드를 캐싱해두었습니다. 즉, 캐싱된 카드 리스트를 가져오기 위해서는 Card의 companion object에 접근해야 합니다.. 그래서 provideCards() 함수가 Card의 companion object에 위치하게 되고 Card와 CardProvider의 의존성이 강해진 것 같습니다.

답변 달다가 생각난 사항인데, Card의 모든 경우의 수를 미리 캐싱해두더라도, Card의 생성자는 public으로 열어두어도 괜찮나요? 저는 외부에서 "캐싱된 Card"가 아닌 "별도의 Card 인스턴스"를 계속 생성하는 것을 막기 위해 private으로 제한해두었는데, 이 부분 때문에 제가 `initCard()`에 대한 리팩터링을 더 어려워하는 것 같네요..

그리고 리뷰 요청 마감까지 다시 미션을 구현해보지는 못 할 것 같지만.. 말씀해주신 조언 참고해서 static 함수를 최대한 지양해보는 방식으로 구현해보겠습니다! 감사합니다.ㅎㅎ

2024-03-17 09:23 UTC, ghojeong commented on src/main/kotlin/blackjack/model/participant/Dealer.kt
> +            else -> super.gameResult(player)
참고로 무엇이 정답이다! 보다는 내 코드가 더 테스트하기 쉬워졌는가?
이 함수가 무엇을 하는지 더 명확해졌는가? 에 집중해주세요!
성능도 물론 고려해야할 요소이지만 지금 성능 말고도 할게 많습니다!

2024-03-17 09:27 UTC, kimhm0728 commented on src/main/kotlin/blackjack/model/Amount.kt
> +    operator fun plus(other: Amount) = Amount(price + other.price)
패키지 분리를 통해 코드를 읽는 사람이 클래스를 이해하는데 더 도움이 될 것이라고 생각했는데, 오히려 혼란을 가져올 수 있다는 사실을 처음 알았습니다.ㅎㅎ 말씀하신대로 아직 패키지 분리의 기준이 명확하게 잡혀있지 않고 클래스 개수가 많지 않다면, model 패키지에 모든 클래스를 위치시키는 것이 더 좋을 것 같네요. 앞으로 다른 미션 진행할 때도 참고하겠습니다! 감사합니다.

2024-03-17 09:30 UTC, ghojeong commented on src/main/kotlin/blackjack/model/participant/Player.kt
>          }
Card 의 생성자를 public 으로 열어두어야 하는지에 대한 고민보다도.
Card 와 연관을 맺는 객체들의 "협력" 관계가 말이 되는지에 대해 고민해주세요.

public 하게 공개된 함수는 생성자를 포함하여, 다른 객체에게 소통의 통로가 되는 메시지 입니다.
public 하게 공개된 요소가 어떤 객체와 협력하기 위해 필요한 것인지, 그 객체와 협력이 말이 되는지, 그리고 public 하게 공개된 로직을 테스트 할 수 있는지에 대해 집중해주세요.

올리브가 굉장히 열심히 해주고 계심에도, 지금 너무 많은 요소를 신경 쓰기 때문에 고민이 점점 많아지게 되는 것 같습니다.
언젠가는 해야할 고민이 맞지만, 한정된 시간내에서 학습해내야할 경험이 있다는 점을 고려해서 우선순위를 말씀드려봅니다.

2024-03-17 09:33 UTC, kimhm0728 commented on src/main/kotlin/blackjack/model/participant/Player.kt
> +        }
사실 1번 질문에서 코드량이 많아진 것 같다고 말씀드린 부분 중 일부는 이 코드였는데요, super를 통해 중복을 어느정도 개선했지만, `Dealer`와 `Player`, `Role`에서 모두 `gameResult()` 함수를 구현하고 있다는 점이 마음에 걸렸습니다.. 그런데 이전 코멘트에서 함수의 역할과 책임이 명확해졌다고 말씀해주시기도 했고, 코드 읽기가 수월하다고 해주셔서 기분이 좋네요. ㅎㅎ 😊

2024-03-17 09:36 UTC, ghojeong commented on src/main/kotlin/blackjack/model/participant/Player.kt
> +        }
> Dealer와 Player, Role에서 모두 gameResult() 함수를 구현하고 있다는 점이 마음에 걸렸습니다.. 

크흡... 예리하시군요. 사실 이 부분 지적할까 하다가, 이 부분에 대한 리팩토링보다는 테스트 코드에 대한 보완이 시급하다고 생각해서 언급하지 않았습니다.

다만 분기조건을 알기쉽게 함수명을 지어주신 것은 정말 보기좋다고 생각한 칭찬입니다!

테스트 코드 보완 후에, 이 부분을 갈아엎는데 욕심이 있으시다면 연락주세요.
도와드리겠습니다.

2024-03-17 18:52 UTC, kimhm0728 commented
파이로! step2에 추가된 요구사항에 대한 테스트 작성했습니다. 그리고 이전 step1 요구사항 테스트도 일부 수정했습니다.
이번 리뷰 반영하면서 느낀 점은, 저는 그동안 요구사항에 대한 테스트를 각각 작성하지 않고, `@ParameterizedTest`를 통해서 하나의 큰 테스트 함수만 구현했다는 것입니다. 동일한 함수에 대한 테스트라면 `@ParameterizedTest`를 통해 테스트 코드의 중복을 개선할 수 있다고 생각했는데, "테스트 코드는 기능 명세서와 유사하다"라는 말이 있듯이 테스트 세분화를 통해서 다른 사람이 빠르게 코드를 이해할 수 있겠다고 생각했습니다..!! 😀

2024-03-17 18:56 UTC, kimhm0728 commented
파이로! step2에 추가된 요구사항에 대한 테스트 작성했습니다. 그리고 이전 step1 요구사항 테스트도 일부 수정했습니다.
이번 리뷰 반영하면서 느낀 점은, 저는 그동안 요구사항에 대한 테스트를 각각 작성하지 않고, `@ParameterizedTest`를 통해서 하나의 큰 테스트 함수만 구현했다는 것입니다. 동일한 함수에 대한 테스트라면 `@ParameterizedTest`를 통해 테스트 코드의 중복을 개선할 수 있다고 생각했는데, "테스트 코드는 기능 명세서와 유사하다"라는 말이 있듯이 테스트 세분화를 통해서 다른 사람이 빠르게 코드를 이해할 수 있겠다고 생각했습니다..!! 😀

2024-03-18 00:51 UTC, ghojeong commented
> 동일한 함수에 대한 테스트라면 `@ParameterizedTest` 를 통해 테스트 코드의 중복을 개선할 수 있다고 생각했는데, "테스트 코드는 기능 명세서와 유사하다"라는 말이 있듯이 테스트 세분화를 통해서 다른 사람이 빠르게 코드를 이해할 수 있겠다고 생각했습니다..!!

ParameterizedTest 를 사용하지 말라는 피드백이라기 보다는, 단위 테스트를 더 세밀하게 작성해달라는 피드백이었습니다!
테스트 코드를 기계가 실행하는 코드가 아니라, 동료가 읽게 되는 코드라 생각해주세요.
그렇다면 동료는 왜 다른 사람의 테스트 코드를 읽을 까요?
올리브가 구현한 특정 객체가 본래 어떤 역할과 책임을 가지고 있는지,
그리고 그 역할에 따라 무슨 기능이 동작해야 하는지 유지보수를 하기 위해서 입니다.

영원히 동작하는 완벽한 코드는 없습니다.
협업을 하는 이상 누군가가 자신이 작성한 코드에 영향받거나 수정해야하는 순간이 옵니다.
그 때 객체에 관한 유의미한 단위 테스트가 없다면,
그 객체를 주변 사람들이 유지보수하기 힘들어집니다.

"테스트 코드는 기능 명세서와 유사하다" 라는 멋진 표현을 해주셨는데,
단위 테스트는 설계한 객체 하나하나가 유의미한 역할과 책임을 가지고 어떻게 다른 객체와 협업하게 될지,
설명하는 명세서라고 생각해주세요. 그리고 그 명세서를 읽는 사람은 언젠가 그 객체를 유지보수할 동료 개발자입니다.

2024-03-18 01:32 UTC, ghojeong commented on src/main/kotlin/blackjack/model/participant/Dealer.kt
>          }
현재 Dealer와 Player, Role에서 모두 gameResult() 함수를 구현하고 있습니다.
함수의 중복이 문제가 아니라 gameResult 로 인해서 분기처리가 점점 많아지는 것이 문제입니다.
위의 Dealer 만 보면, DRAW, BLACKJACK_LOSE, WIN, LOSE 4 가지 경우에 대한 분기처리 같지만,
super 까지 고려하면 3가지 경우에 대한 분기처리가 추가됩니다.

Player 에도 Dealer 와 마찬가지로 4가지에 대한 분기처리가 있으므로,
gameResult 함수를 제대로 검증하려면 (3+4) + (3+4) = 14 개의 테스트를 작성해야합니다.
그리고 이 분기는 혹여나 예외가 추가될 때마다 계속 늘어날 것입니다.

이를 해결하기 위해서 다형성(Polymorphism) 을 도입해보자고 제안을 해봅니다.
GameResult 를 최종 마지막 결과가 아니라 현재 진행중인 GameState 라 생각하고,
게임이 진행하면서 GameState 가 수시로 바뀌도록 해주세요. (`var GameState`)

if 혹은 when 을 통해 분기되어야 하는 로직은 `abstract fun` 에 따라,
State 가 달라지면 알아서 다른 로직이 실행되도록 다형성을 활용해주시기 바랍니다.

2024-03-18 05:03 UTC, kimhm0728 commented
> ParameterizedTest 를 사용하지 말라는 피드백이라기 보다는, 단위 테스트를 더 세밀하게 작성해달라는 피드백이었습니다!

아! 파이로 피드백은 완전히 이해했습니다 😀 이전 제 코드에서는 ParameterizedTest 를 사용함으로써 포괄적인 테스트를 작성했고, ParameterizedTest 사용을 줄이는 방식으로 테스트를 세분화할 수 있을 것 같아 말씀드렸습니다. 앞으로 유의미한 테스트 작성에 더 신경쓰도록 하겠습니다 감사합니다. ㅎㅎ

각 상태에 대해 다형성을 활용해서 분기처리를 최대한 없애보도록 하겠습니다~ 반영 후 다시 요청드리겠습니다!

2024-03-19 10:02 UTC, ghojeong approved these changes
올리브!
DM 을 포함해서 굉장히 많은 이야기를 나누어주셨는데,
제가 더 일찍 방향을 잡아주지 못해서 살짝 아쉬움이 남네요.
모든 내용을 학습하지 못한 것에 크게 마음 두지 마시고,
다음 미션에 가셔서 다음 미션에서 배울 수 있는 경험에 집중해 주시기 바랍니다!
미션 완주까지 화이팅입니다. 💪

2024-03-19 10:02 UTC, merged